import type { AssessmentDef } from "../types";

/** Final assessment for Data Modelling. Options are shuffled when shown. */
export const DMO_ASSESSMENT: AssessmentDef = {
  id: "data-modelling-final",
  courseId: "data-modelling",
  title: "Data Modelling: final assessment",
  passingScore: 60,
  questions: [
    {
      id: "dmoq01",
      prompt: "At which level of a data model are data types such as INT and DATE decided?",
      options: ["Conceptual", "Logical", "Physical", "None of the levels"],
      answer: 2,
      explanation: "Data types belong to a specific database, so they're physical.",
    },
    {
      id: "dmoq02",
      prompt: "An attendance table has one row per employee per working day. What is this statement called?",
      options: ["The primary key", "The grain", "The cardinality", "The schema"],
      answer: 1,
      explanation: "The grain says what one row represents.",
    },
    {
      id: "dmoq03",
      prompt: "Which column is the best primary key for a customers table?",
      options: ["customer_name", "phone", "A system-assigned customer_id", "city"],
      answer: 2,
      explanation: "A surrogate ID is unique, always present and never changes.",
    },
    {
      id: "dmoq04",
      prompt: "In a one-to-many relationship between customers and orders, where does the foreign key go?",
      options: ["On customers", "On orders", "In a separate table", "On both tables"],
      answer: 1,
      explanation: "The many side holds the key of the one side.",
    },
    {
      id: "dmoq05",
      prompt: "Students take many courses and courses have many students. How is this modelled?",
      options: ["A course_ids column listing IDs on students", "A bridge table with one row per student per course", "One big table", "A self-relationship"],
      answer: 1,
      explanation: "A bridge (junction) table turns many-to-many into two one-to-manys.",
    },
    {
      id: "dmoq06",
      prompt: "In crow's-foot notation, what does the crow's foot (the three-pronged end) mean?",
      options: ["Many", "Exactly one", "None", "The primary key"],
      answer: 0,
      explanation: "The crow's foot marks the 'many' side of a relationship.",
    },
    {
      id: "dmoq07",
      prompt: "A shipment row refers to customer_id 999, but no customer 999 exists. What is this row called?",
      options: ["A duplicate", "An orphan", "A composite key", "A dimension"],
      answer: 1,
      explanation: "It breaks referential integrity and drops out of inner joins.",
    },
    {
      id: "dmoq08",
      prompt: "A table has columns item1, item2, item3. Which normal form does it break?",
      options: ["First normal form", "Second normal form", "Third normal form", "It is fully normalised"],
      answer: 0,
      explanation: "Repeating groups break 1NF.",
    },
    {
      id: "dmoq09",
      prompt: "What is the main goal of normalisation?",
      options: ["Store each fact once, so data isn't repeated or contradictory", "Make tables wider", "Add more columns to each table", "Make reports load colourfully"],
      answer: 0,
      explanation: "Normalising splits repeated information into its own table, so each fact lives in one place.",
    },
    {
      id: "dmoq10",
      prompt: "A customer's phone number is stored in both the customers table and the orders table. What is the risk?",
      options: ["None", "The two copies can disagree after one is updated", "The database will refuse to save it", "Orders will be deleted"],
      answer: 1,
      explanation: "Storing the same fact twice lets the copies drift apart. Keep it in one table.",
    },
    {
      id: "dmoq11",
      prompt: "Which belongs in a fact table?",
      options: ["Product category", "Customer region", "Quantity sold", "Sales rep's name"],
      answer: 2,
      explanation: "Facts are the numbers you add up at the fact table's grain.",
    },
    {
      id: "dmoq12",
      prompt: "What should be decided first when designing a fact table?",
      options: ["The dimensions", "The grain", "The report colours", "The database product"],
      answer: 1,
      explanation: "Every measure must be true at the grain.",
    },
    {
      id: "dmoq13",
      prompt: "Why is a star schema usually preferred to a snowflake in Power BI?",
      options: ["Snowflakes can't hold numbers", "Fewer relationships make filtering simpler and faster", "Stars never repeat values", "Power BI can't load snowflakes"],
      answer: 1,
      explanation: "Each extra hop is another relationship for filters to travel through.",
    },
    {
      id: "dmoq14",
      prompt: "A customer moves to a new region, but old orders must still be reported under the old region. What should you do in the customer dimension?",
      options: ["Overwrite the region (type 1)", "Add a new row for the customer with the new region (type 2)", "Delete the customer", "Ignore the move"],
      answer: 1,
      explanation: "A type 2 slowly changing dimension keeps history by adding a new row.",
    },
    {
      id: "dmoq15",
      prompt: "A primary key must be:",
      options: ["Unique for every row and never empty", "Text", "The first column in the table", "A number you can add up"],
      answer: 0,
      explanation: "Each row needs its own key value, and it can't be missing.",
    },
  ],
};
