import type { AssessmentDef } from "../types";

/** Final assessment for Data Modelling. Options are shuffled when shown. */
export const DMO_ASSESSMENT: AssessmentDef = {
  id: "data-modelling-final",
  courseId: "data-modelling",
  title: "Data Modelling: final assessment",
  passingScore: 70,
  questions: [
    {
      id: "dmoq01",
      prompt: "At which level of a data model are data types such as INT and DATE decided?",
      options: ["Conceptual", "Logical", "Physical", "None of the levels"],
      answer: 2,
      explanation: "Data types belong to a specific database, so they're physical.",
    },
    {
      id: "dmoq02",
      prompt: "An attendance table has one row per employee per working day. What is this statement called?",
      options: ["The primary key", "The grain", "The cardinality", "The schema"],
      answer: 1,
      explanation: "The grain says what one row represents.",
    },
    {
      id: "dmoq03",
      prompt: "Which column is the best primary key for a customers table?",
      options: ["customer_name", "phone", "A system-assigned customer_id", "city"],
      answer: 2,
      explanation: "A surrogate ID is unique, always present and never changes.",
    },
    {
      id: "dmoq04",
      prompt: "In a one-to-many relationship between customers and orders, where does the foreign key go?",
      options: ["On customers", "On orders", "In a separate table", "On both tables"],
      answer: 1,
      explanation: "The many side holds the key of the one side.",
    },
    {
      id: "dmoq05",
      prompt: "Students take many courses and courses have many students. How is this modelled?",
      options: ["A course_ids column listing IDs on students", "A bridge table with one row per student per course", "One big table", "A self-relationship"],
      answer: 1,
      explanation: "A bridge (junction) table turns many-to-many into two one-to-manys.",
    },
    {
      id: "dmoq06",
      prompt: "In crow's-foot notation, a circle next to a crow's foot means:",
      options: ["Exactly one", "Zero or many", "One or many", "Zero or one"],
      answer: 1,
      explanation: "The circle means zero is allowed; the crow's foot means many.",
    },
    {
      id: "dmoq07",
      prompt: "A shipment row refers to customer_id 999, but no customer 999 exists. What is this row called?",
      options: ["A duplicate", "An orphan", "A composite key", "A dimension"],
      answer: 1,
      explanation: "It breaks referential integrity and drops out of inner joins.",
    },
    {
      id: "dmoq08",
      prompt: "A table has columns item1, item2, item3. Which normal form does it break?",
      options: ["First normal form", "Second normal form", "Third normal form", "It is fully normalised"],
      answer: 0,
      explanation: "Repeating groups break 1NF.",
    },
    {
      id: "dmoq09",
      prompt: "In a line table keyed by (invoice_id, product_id), invoice_date depends only on invoice_id. Which rule is broken?",
      options: ["1NF", "2NF: a column depends on only part of the key", "3NF", "No rule"],
      answer: 1,
      explanation: "Partial dependency on a composite key breaks 2NF.",
    },
    {
      id: "dmoq10",
      prompt: "In a customers table, region depends on city rather than on the customer key. Which normal form does that break?",
      options: ["1NF", "2NF", "3NF: a non-key column depends on another non-key column", "None"],
      answer: 2,
      explanation: "Transitive dependencies break 3NF.",
    },
    {
      id: "dmoq11",
      prompt: "Which belongs in a fact table?",
      options: ["Product category", "Customer region", "Quantity sold", "Sales rep's name"],
      answer: 2,
      explanation: "Facts are the numbers you add up at the fact table's grain.",
    },
    {
      id: "dmoq12",
      prompt: "What should be decided first when designing a fact table?",
      options: ["The dimensions", "The grain", "The report colours", "The database product"],
      answer: 1,
      explanation: "Every measure must be true at the grain.",
    },
    {
      id: "dmoq13",
      prompt: "Why is a star schema usually preferred to a snowflake in Power BI?",
      options: ["Snowflakes can't hold numbers", "Fewer relationships make filtering simpler and faster", "Stars never repeat values", "Power BI can't load snowflakes"],
      answer: 1,
      explanation: "Each extra hop is another relationship for filters to travel through.",
    },
    {
      id: "dmoq14",
      prompt: "A customer moves region and old orders must keep reporting under the old region. Which technique?",
      options: ["Slowly changing dimension type 1", "Slowly changing dimension type 2", "Delete and re-add the customer", "Store region on the fact table as text only"],
      answer: 1,
      explanation: "Type 2 adds a new dimension row and keeps the old one for past facts.",
    },
    {
      id: "dmoq15",
      prompt: "Which check confirms a column can be a primary key?",
      options: ["SUM of the column", "COUNT(*) equals COUNT(DISTINCT column) and no NULLs", "The column is text", "The column is the first in the table"],
      answer: 1,
      explanation: "A primary key must be unique and never empty.",
    },
  ],
};
