import type { AssessmentDef } from "../types";

/** Final assessment for Excel for Data Analysis. Options are shuffled when shown. */
export const XLS_ASSESSMENT: AssessmentDef = {
  id: "excel-for-data-analysis-final",
  courseId: "excel-for-data-analysis",
  title: "Excel for Data Analysis: final assessment",
  passingScore: 70,
  questions: [
    {
      id: "xlsq01",
      prompt: "Why import a CSV with Data → From Text/CSV instead of double-clicking it?",
      options: ["It is the only way to open a CSV", "You can check and set column types before the data loads", "It removes duplicates automatically", "It makes the numbers smaller"],
      answer: 1,
      explanation: "Checking types up front prevents lost leading zeros, scientific notation and misread dates.",
    },
    {
      id: "xlsq02",
      prompt: "In an Excel Table, what does =[@quantity]*[@unit_price] calculate?",
      options: ["The total of both columns", "Quantity times unit price for the same row", "The first row only", "An error, because @ isn't allowed"],
      answer: 1,
      explanation: "[@column] refers to the value in the current row.",
    },
    {
      id: "xlsq03",
      prompt: "You filter a table to Lagos. Which formula totals only the visible revenue cells in H2:H500?",
      options: ["=SUM(H2:H500)", "=SUBTOTAL(9, H2:H500)", "=COUNT(H2:H500)", "=TOTAL(H2:H500)"],
      answer: 1,
      explanation: "SUBTOTAL ignores rows hidden by a filter; SUM doesn't.",
    },
    {
      id: "xlsq04",
      prompt: "=C2*$F$1 is copied from row 2 down to row 10. What does it become?",
      options: ["=C10*$F$9", "=C10*$F$1", "=C2*$F$1", "=K10*$F$1"],
      answer: 1,
      explanation: "The relative reference moves; the absolute one stays.",
    },
    {
      id: "xlsq05",
      prompt: "A column has 50 numbers, 10 text values and 5 blanks. What does =COUNTA() of it return?",
      options: ["50", "55", "60", "65"],
      answer: 2,
      explanation: "COUNTA counts every non-empty cell: 50 + 10 = 60.",
    },
    {
      id: "xlsq06",
      prompt: "A cell shows #N/A after an XLOOKUP. What does it usually mean?",
      options: ["Division by zero", "No match was found for the lookup value", "The formula is misspelled", "The cell was deleted"],
      answer: 1,
      explanation: "#N/A means the value wasn't found, often because of spaces or text-vs-number IDs.",
    },
    {
      id: "xlsq07",
      prompt: "Which formula totals revenue (column H) for rows where region (column D) is \"Lagos\" and channel (column C) is \"Wholesale\"?",
      options: [
        "=SUMIF(D:D, \"Lagos\", H:H, C:C, \"Wholesale\")",
        "=SUMIFS(H:H, D:D, \"Lagos\", C:C, \"Wholesale\")",
        "=SUM(IF(D:D=\"Lagos\"))",
        "=COUNTIFS(H:H, \"Lagos\", \"Wholesale\")",
      ],
      answer: 1,
      explanation: "SUMIFS takes the sum range first, then pairs of range and condition.",
    },
    {
      id: "xlsq08",
      prompt: "How do you write a SUMIFS condition for dates on or after 1 October 2025?",
      options: ["\">=1/10/2025\"", "\">=\"&DATE(2025,10,1)", ">=DATE(2025,10,1)", "\"DATE>=2025-10-01\""],
      answer: 1,
      explanation: "Join the operator as text to a real date made with DATE().",
    },
    {
      id: "xlsq09",
      prompt: "=XLOOKUP(A2, Products[product_id], Products[category], \"Missing\"). What is returned when A2 isn't in the product list?",
      options: ["#N/A", "0", "Missing", "The first category"],
      answer: 2,
      explanation: "The fourth argument is the value to return when there is no match.",
    },
    {
      id: "xlsq10",
      prompt: "Why is VLOOKUP(A2, Sheet2!A:F, 4, FALSE) considered fragile?",
      options: ["It only works on numbers", "Inserting a column in the lookup range shifts what column 4 points to", "FALSE returns approximate matches", "It can't search more than 4 columns"],
      answer: 1,
      explanation: "The hard-coded column number doesn't adjust when the table's layout changes.",
    },
    {
      id: "xlsq11",
      prompt: "What does =PROPER(TRIM(\"  KAYODE   STORES \")) return?",
      options: ["\"KAYODE STORES\"", "\"Kayode Stores\"", "\"kayode stores\"", "\"  Kayode   Stores \""],
      answer: 1,
      explanation: "TRIM removes the extra spaces; PROPER capitalises each word.",
    },
    {
      id: "xlsq12",
      prompt: "Excel's Remove Duplicates treats \"Ada Mart\" and \"Ada Mart \" (with a trailing space) as:",
      options: ["Duplicates", "Different values", "An error", "Blank"],
      answer: 1,
      explanation: "Spaces count as characters. Trim before removing duplicates.",
    },
    {
      id: "xlsq13",
      prompt: "You added new rows to the Table a pivot table is built on. How do you include them?",
      options: ["Rebuild the pivot", "Refresh the pivot (Data → Refresh All)", "Nothing, pivots update themselves", "Copy the rows into the pivot"],
      answer: 1,
      explanation: "Pivots are snapshots until refreshed; a pivot on a Table picks up new rows when refreshed.",
    },
    {
      id: "xlsq14",
      prompt: "Which pivot setting shows each channel's revenue as a share of all revenue?",
      options: ["Summarise Values By → Count", "Show Values As → % of Grand Total", "Group → Years", "Insert Slicer"],
      answer: 1,
      explanation: "Show Values As expresses each value relative to the grand total.",
    },
    {
      id: "xlsq15",
      prompt: "Which chart best shows how revenue changed month by month over 18 months?",
      options: ["Pie chart", "Line chart", "Scatter chart", "Doughnut chart"],
      answer: 1,
      explanation: "Line charts show trends over time.",
    },
  ],
};
