import type { AssessmentDef } from "../types";

/** Final assessment for Data Analytics Foundations. Options are shuffled when shown. */
export const DAF_ASSESSMENT: AssessmentDef = {
  id: "data-analytics-foundations-final",
  courseId: "data-analytics-foundations",
  title: "Data Analytics Foundations: final assessment",
  passingScore: 60,
  questions: [
    {
      id: "dafq01",
      prompt: "A manager asks \"Why did deliveries to Kano get slower last quarter?\" Which kind of analytics question is this?",
      options: ["Descriptive", "Diagnostic", "Predictive", "Prescriptive"],
      answer: 1,
      explanation: "It asks why something happened.",
    },
    {
      id: "dafq02",
      prompt: "Which of these is the most useful, measurable version of \"How is the business doing?\"",
      options: [
        "How is the business doing overall?",
        "How did revenue in January–June 2026 compare with January–June 2025, by region?",
        "Show me all the data we have.",
        "Is the business good or bad?",
      ],
      answer: 1,
      explanation: "It names the measure, the periods, the comparison and the breakdown.",
    },
    {
      id: "dafq03",
      prompt: "An on-time delivery rate is calculated as:",
      options: ["Late deliveries ÷ on-time deliveries × 100", "On-time deliveries ÷ all deliveries × 100", "All deliveries − late deliveries", "Late deliveries ÷ all deliveries"],
      answer: 1,
      explanation: "The share of all deliveries that arrived on time.",
    },
    {
      id: "dafq04",
      prompt: "Revenue went from ₦50m to ₦60m. What is the growth rate?",
      options: ["10%", "16.7%", "20%", "120%"],
      answer: 2,
      explanation: "(60 − 50) ÷ 50 × 100 = 20%.",
    },
    {
      id: "dafq05",
      prompt: "Which column is qualitative and ordinal?",
      options: ["Customer region", "Monthly salary", "Job level: Junior, Mid, Senior, Manager", "Order date"],
      answer: 2,
      explanation: "Job levels are categories with a natural order.",
    },
    {
      id: "dafq06",
      prompt: "In an orders table, one row is one product on one order. What is this called?",
      options: ["The grain of the table", "The primary key", "An outlier", "A dashboard"],
      answer: 0,
      explanation: "The grain says what one row represents.",
    },
    {
      id: "dafq07",
      prompt: "customer_id appears in both the customers table and the orders table. In the orders table it is a:",
      options: ["Primary key", "Foreign key", "Measure", "Duplicate"],
      answer: 1,
      explanation: "It points to the primary key of another table.",
    },
    {
      id: "dafq08",
      prompt: "A customer list has \"Ada Superstore\" and \"  ADA SUPERSTORE\". What must happen before removing duplicates?",
      options: ["Sort by region", "Trim the spaces and make the capitals consistent", "Delete both rows", "Convert the names to numbers"],
      answer: 1,
      explanation: "Until they're trimmed and in the same case, the two rows don't look identical.",
    },
    {
      id: "dafq09",
      prompt: "Why should you keep the original data file untouched when cleaning?",
      options: [
        "Spreadsheets can't edit CSV files",
        "It lets you check or redo your work, and proves what the source said",
        "Cleaned data is always wrong",
        "It makes the file smaller",
      ],
      answer: 1,
      explanation: "The raw file is your safety net and your evidence.",
    },
    {
      id: "dafq10",
      prompt: "Most staff earn ₦300,000–₦600,000 but three directors earn ₦5,000,000. Which figure best describes a typical salary?",
      options: ["Mean", "Median", "Maximum", "Total"],
      answer: 1,
      explanation: "The directors pull the mean up; the median stays with typical staff.",
    },
    {
      id: "dafq11",
      prompt: "Which chart best shows how monthly revenue changed over 18 months?",
      options: ["Pie chart", "Line chart", "Scatter plot", "3D column chart"],
      answer: 1,
      explanation: "Line charts show trends over time.",
    },
    {
      id: "dafq12",
      prompt: "A bar chart's axis starts at ₦40m instead of zero. What is the problem?",
      options: ["Nothing", "Bar lengths exaggerate the differences between categories", "The colours will be wrong", "It can't show negative numbers"],
      answer: 1,
      explanation: "Bar length is read as size, so the baseline must be zero.",
    },
    {
      id: "dafq13",
      prompt: "What does a BI dashboard mainly do?",
      options: [
        "Replaces the need for any data cleaning",
        "Monitors agreed KPIs repeatedly from refreshed data",
        "Stores the company's raw data",
        "Answers a new question once",
      ],
      answer: 1,
      explanation: "BI is about monitoring the same important measures, reliably and repeatedly.",
    },
    {
      id: "dafq14",
      prompt: "Revenue in one region fell, but the same customers were still ordering. Which explanation does this rule out?",
      options: ["Customers ordering less often", "Smaller orders", "Losing customers", "Lower prices"],
      answer: 2,
      explanation: "If the same customers still order, lost customers aren't the cause.",
    },
    {
      id: "dafq15",
      prompt: "A department of 5 people had 2 resignations (40%). What is the most responsible way to report this?",
      options: [
        "Say this department has a turnover crisis",
        "Leave it out because it's small",
        "Report the rate with the counts (2 of 5) and note that small groups make rates jumpy",
        "Round it to 50%",
      ],
      answer: 2,
      explanation: "Show counts beside rates and state the limits of small numbers.",
    },
  ],
};
