/**
 * The course catalogue. This is the source content: it is bundled into the site
 * (so public pages are prerendered for search engines) and, in Supabase mode, it
 * is also loaded into the database by `npm run seed` so it can be managed from /admin.
 */

import type { Level } from "./tracks";

export type Difficulty = "beginner" | "intermediate" | "advanced";
export type CourseStatus = "available" | "coming_soon";

export type Category = { id: string; name: string; description: string; future?: boolean };

export const CATEGORIES: Category[] = [
  { id: "ai-productivity", name: "AI & Productivity", description: "Use AI tools to research, write, create and work faster." },
  { id: "design-content", name: "Design & Content", description: "Design graphics, edit videos and plan content." },
  { id: "career", name: "Career", description: "CVs, LinkedIn and the digital skills employers look for." },
  { id: "study-skills", name: "Study & Digital Skills", description: "Study, research and work smarter with AI and everyday digital tools." },
  { id: "coding", name: "Coding & Web", description: "Git, GitHub and building your first websites." },
  { id: "data-analytics", name: "Data Analytics", description: "Turning raw data into answers a business can act on." },
  { id: "business-intelligence", name: "Business Intelligence", description: "Dashboards, reporting and data models." },
  { id: "data-science", name: "Data Science", description: "Statistics and predictive modelling.", future: true },
  { id: "ai-ml", name: "AI & Machine Learning", description: "Building and applying machine learning models.", future: true },
  { id: "python", name: "Python", description: "Python for analysis and automation." },
  { id: "databases", name: "Databases & Data Modelling", description: "Designing databases and data models that answer business questions." },
  { id: "automation", name: "Automation", description: "Automating repetitive work.", future: true },
  { id: "business-analysis", name: "Business Analysis", description: "Requirements, processes and decisions." },
  { id: "cloud", name: "Cloud & Technology", description: "Cloud platforms and core technology skills.", future: true },
];

export type CertificateRules = {
  enabled: boolean;
  requireAllLessons: boolean;
  requireExercises: boolean;
  requireProject: boolean;
  /** Every module with a module assessment must have its badge. */
  requireModuleBadges: boolean;
  passingScore: number;
};

export type ModuleDef = {
  id: string;
  title: string;
  lessons: string[];
  /** Name of the badge earned by passing this module's assessment, e.g. "Prompting Essentials". */
  badge?: string;
  /** Short code used in the badge's credential ID, e.g. CTA-PROMPT-8F72K. */
  badgeCode?: string;
  /** Skills shown on the module badge's public credential page. */
  skills?: string[];
};

export type CourseDef = {
  id: string;
  /** "short": modules of 15–30 minutes, each with a check and a badge. "full": longer lessons with practice. Default "full". */
  format?: "full" | "short";
  /** Name of the course completion badge. Defaults to the course title. */
  completionBadge?: string;
  slug: string;
  /** Short code used in credential IDs, e.g. CTA-SQL-2026-004821 */
  code: string;
  title: string;
  summary: string;
  description: string;
  categoryId: string;
  difficulty: Difficulty;
  /** 1 Foundations, 2 Practical Skills, 3 Professional, 4 Career Projects (see LEVELS in tracks.ts). */
  level: Level;
  levelLabel: string;
  /**
   * Study time for the required path, shown on cards: the lessons' minutes (which npm run
   * test:content keeps honest) plus the final project and assessment. Optional drills are extra.
   * Undefined while a course is in preparation.
   */
  estimatedHours?: number;
  isFree: boolean;
  status: CourseStatus;
  skills: string[];
  prerequisites: string[];
  projectTitle?: string;
  certificate: CertificateRules;
  /** Module titles in order; `lessons` lists lesson slugs (files in src/content/<course>/). */
  modules: ModuleDef[];
};

const rules = (requireProject: boolean): CertificateRules => ({
  enabled: true,
  requireAllLessons: true,
  requireExercises: true,
  requireProject,
  requireModuleBadges: false,
  passingScore: 60,
});

/** Short courses: every module badge, then the final assessment. No lesson ticking or practice required. */
const shortRules: CertificateRules = {
  enabled: true,
  requireAllLessons: false,
  requireExercises: false,
  requireProject: false,
  requireModuleBadges: true,
  passingScore: 60,
};

export const COURSES: CourseDef[] = [
  {
    id: "ai-productivity-fundamentals",
    slug: "ai-productivity-fundamentals",
    format: "short",
    code: "AIPF",
    title: "AI Productivity Fundamentals",
    completionBadge: "AI Productivity Fundamentals",
    summary: "Use AI tools to research, write and create faster: prompting, Claude, ChatGPT and presentations, in four short modules.",
    description:
      "Learn practical ways to use AI assistants at work, at school and in your business. Write prompts that get useful answers, work with your own documents in Claude, research with sources in ChatGPT, and turn an idea into a presentation. Each module takes about 30 minutes, including tasks you do yourself, and ends with a check and a badge.",
    categoryId: "ai-productivity",
    difficulty: "beginner",
    level: 1,
    levelLabel: "Beginner",
    isFree: true,
    status: "available",
    skills: ["Writing clear prompts", "Working with documents in Claude", "Researching with ChatGPT", "Building presentations with AI", "Checking AI answers before you use them"],
    prerequisites: ["No experience needed", "A free account with any AI assistant, such as ChatGPT or Claude"],
    certificate: shortRules,
    modules: [
      { id: "aipf-m01", title: "Prompting Essentials", lessons: ["prompting-essentials"], badge: "Prompting Essentials", badgeCode: "PROMPT", skills: ["Write a prompt with context, task and format", "Give examples so the AI matches your style", "Improve a weak answer instead of starting again", "Check AI answers before you use them"] },
      { id: "aipf-m02", title: "Using Claude", lessons: ["using-claude"], badge: "Claude AI Essentials", badgeCode: "CLAUDE", skills: ["Start a conversation and follow up well", "Summarise and question a document you upload", "Rewrite text for a different reader or tone", "Keep ongoing work organised in a project"] },
      { id: "aipf-m03", title: "Using ChatGPT", lessons: ["using-chatgpt"], badge: "ChatGPT Essentials", badgeCode: "CHATGPT", skills: ["Ask focused questions and refine the answer", "Use files and images in a chat", "Research with sources you can check", "Save your preferences so every chat starts better"] },
      { id: "aipf-m04", title: "Presentations with AI", lessons: ["presentations-with-ai"], badge: "AI Presentations", badgeCode: "SLIDES", skills: ["Get a slide-by-slide outline from an AI assistant", "Write short, clear slide text and speaker notes", "Build the deck quickly in PowerPoint, Google Slides or Canva", "Check the facts and make it sound like you"] },
    ],
  },
  {
    id: "design-content-essentials",
    slug: "design-content-essentials",
    format: "short",
    code: "DCE",
    title: "Design & Content Essentials",
    completionBadge: "Design & Content Essentials",
    summary: "Plan social content with AI, design professional graphics in Canva and edit short videos in CapCut, in three short modules.",
    description:
      "Create content people stop scrolling for. Plan a month of posts and write captions in your brand voice with AI, design clean graphics in Canva using four simple rules, and edit a short vertical video in CapCut with captions and music. Each module takes 30 to 40 minutes, including tasks you do yourself, and ends with a check and a badge.",
    categoryId: "design-content",
    difficulty: "beginner",
    level: 1,
    levelLabel: "Beginner",
    isFree: true,
    status: "available",
    skills: ["Planning a content calendar", "Captions in your brand voice", "Designing in Canva", "Editing short videos in CapCut"],
    prerequisites: ["No experience needed", "A phone or computer; Canva and CapCut are free to start"],
    certificate: shortRules,
    modules: [
      { id: "dce-m01", title: "Social Media Content with AI", lessons: ["social-media-content-with-ai"], badge: "AI Social Content", badgeCode: "SOCIAL", skills: ["Pick three content themes for your page", "Plan a simple content calendar with AI", "Write captions that match your brand voice", "Repurpose one idea across platforms"] },
      { id: "dce-m02", title: "Design with Canva", lessons: ["design-with-canva"], badge: "Canva Design Essentials", badgeCode: "CANVA", skills: ["Start from the right template and size", "Apply four rules: contrast, alignment, spacing, few fonts", "Add your own photos, colours and logo", "Download in the right format and resize for other platforms"] },
      { id: "dce-m03", title: "Video Editing with CapCut", lessons: ["video-editing-with-capcut"], badge: "CapCut Video Essentials", badgeCode: "CAPCUT", skills: ["Start a project in the right size for Reels, TikTok or Shorts", "Trim and split clips to keep only the best parts", "Add text, automatic captions and music", "Export in good quality for social media"] },
    ],
  },
  {
    id: "career-essentials",
    slug: "career-essentials",
    format: "short",
    code: "CAREER",
    title: "Career Essentials",
    completionBadge: "Career Essentials",
    summary: "Build a CV with AI, set up a professional LinkedIn profile and analyse Excel data quickly, in three short modules.",
    description:
      "Get ready for your next job. Use AI to write and tailor a CV that stays true to you, set up a LinkedIn profile recruiters can find, and learn the Excel basics employers expect: sorting, filtering, formulas, PivotTables and charts. Each module takes about 30 minutes, including tasks you do yourself, and ends with a check and a badge.",
    categoryId: "career",
    difficulty: "beginner",
    level: 1,
    levelLabel: "Beginner",
    isFree: true,
    status: "available",
    skills: ["Achievement-focused CV writing", "Tailoring a CV to a job", "A recruiter-ready LinkedIn profile", "Quick analysis in Excel"],
    prerequisites: ["No experience needed", "Excel or Google Sheets for the last module"],
    certificate: shortRules,
    modules: [
      { id: "career-m01", title: "Build a CV with AI", lessons: ["build-a-cv-with-ai"], badge: "AI CV Builder", badgeCode: "CV", skills: ["Lay out a clear, recruiter-friendly CV", "Turn duties into achievement bullet points", "Tailor your CV to a job advert", "Check the result so nothing is exaggerated"] },
      { id: "career-m02", title: "A Professional LinkedIn Profile", lessons: ["linkedin-profile"], badge: "LinkedIn Profile Essentials", badgeCode: "LINKEDIN", skills: ["Choose a professional photo and banner", "Write a headline people search for", "Write an About section that tells your story", "Show your skills, experience and badges"] },
      { id: "career-m03", title: "Quick Excel Analysis", lessons: ["quick-excel-analysis"], badge: "Excel Quick Analysis", badgeCode: "EXCEL", skills: ["Turn data into an Excel Table", "Sort and filter to find what matters", "Total and count with SUM, AVERAGE and COUNTIF", "Summarise with a PivotTable and a chart"] },
    ],
  },
  {
    id: "chatgpt-for-students",
    slug: "chatgpt-for-students",
    format: "short",
    code: "AISTU",
    title: "ChatGPT & AI for Students",
    completionBadge: "AI for Students",
    summary: "Use ChatGPT and other AI tools to understand topics, revise, research and write, honestly and within your school's rules.",
    description:
      "Learn how AI assistants work and where they go wrong, then use them to study smarter: explain hard topics, make revision questions, plan research and improve your writing without handing in work that isn't yours. Each module takes 20 to 30 minutes, including tasks you do yourself, and ends with a check and a badge.",
    categoryId: "study-skills",
    difficulty: "beginner",
    level: 1,
    levelLabel: "Beginner",
    isFree: true,
    status: "available",
    skills: ["How AI assistants work and their limits", "Studying and revising with AI", "Researching with AI and checking sources", "Using AI in writing honestly"],
    prerequisites: ["No experience needed", "A free account with ChatGPT or another AI assistant"],
    certificate: shortRules,
    modules: [
      { id: "aistu-m01", title: "AI Fundamentals for Students", lessons: ["ai-fundamentals"], badge: "AI Fundamentals", badgeCode: "AIBASICS", skills: ["Explain what ChatGPT actually is", "Know what AI is good and bad at", "Spot made-up facts and references", "Follow your school's rules on AI use"] },
      { id: "aistu-m02", title: "Study Smarter with AI", lessons: ["study-with-ai"], badge: "AI Study Skills", badgeCode: "STUDYAI", skills: ["Ask for explanations, not answers", "Test yourself with AI-made questions", "Turn notes into study tools", "Plan your revision"] },
      { id: "aistu-m03", title: "Research with AI", lessons: ["research-with-ai"], badge: "AI Research", badgeCode: "AIRESRCH", skills: ["Know where AI helps in research and where it doesn't", "Get an overview and search terms", "Check every AI reference before using it", "Summarise and question real sources"] },
      { id: "aistu-m04", title: "Writing with AI, Honestly", lessons: ["writing-with-ai"], badge: "Honest AI Writing", badgeCode: "AIWRITE", skills: ["Use AI as a coach, not a ghostwriter", "Plan your writing before you start", "Get feedback on your own draft", "Say how you used AI"] },
    ],
  },
  {
    id: "research-skills-for-students",
    slug: "research-skills-for-students",
    format: "short",
    code: "RSRCH",
    title: "Research Skills for Students",
    completionBadge: "Research Skills",
    summary: "Search the web and academic databases like a pro, judge which sources to trust, and cite them properly.",
    description:
      "Find better information faster. Use search operators and Google Scholar, check whether a source is reliable, and cite and organise references so assignments and projects are easy to write. Each module takes 25 to 35 minutes, including tasks you do yourself, and ends with a check and a badge.",
    categoryId: "study-skills",
    difficulty: "beginner",
    level: 1,
    levelLabel: "Beginner",
    isFree: true,
    status: "available",
    skills: ["Advanced Google and Google Scholar searches", "Judging whether a source is reliable", "Citing sources correctly", "Organising references"],
    prerequisites: ["No experience needed"],
    certificate: shortRules,
    modules: [
      { id: "rsrch-m01", title: "Search Like a Pro", lessons: ["search-like-a-pro"], badge: "Smart Search", badgeCode: "SEARCH", skills: ["Choose better keywords", "Use search operators to narrow results", "Search Google Scholar and trusted sites", "Refine searches as you go"] },
      { id: "rsrch-m02", title: "Judge Your Sources", lessons: ["judge-your-sources"], badge: "Source Evaluation", badgeCode: "SOURCES", skills: ["Tell stronger sources from weaker ones", "Check five things about any source", "Read laterally to verify claims", "Spot red flags"] },
      { id: "rsrch-m03", title: "Cite and Organise Your Sources", lessons: ["cite-and-organise"], badge: "Citation Skills", badgeCode: "CITE", skills: ["Explain why citing matters", "Quote, paraphrase and summarise correctly", "Cite in your department's style", "Format and organise references with a free tool"] },
    ],
  },
  {
    id: "build-your-student-portfolio",
    slug: "build-your-student-portfolio",
    format: "short",
    code: "PORTF",
    title: "Build Your Student Portfolio",
    completionBadge: "Student Portfolio",
    summary: "Choose your best work, present it clearly, publish a one-link portfolio page and share it on LinkedIn.",
    description:
      "A portfolio shows what you can do, which matters most when you don't have much work experience yet. Pick your three best pieces, present each one clearly, publish a simple portfolio page for free, and share your work on LinkedIn without sounding like you're bragging. Each module takes 20 to 25 minutes, including tasks you do yourself, and ends with a check and a badge.",
    categoryId: "career",
    difficulty: "beginner",
    level: 1,
    levelLabel: "Beginner",
    isFree: true,
    status: "available",
    skills: ["Choosing and describing portfolio projects", "Presenting and sharing work safely", "Publishing a free portfolio page", "Writing LinkedIn posts about your work"],
    prerequisites: ["No experience needed", "At least one project, assignment or activity you're proud of"],
    certificate: shortRules,
    modules: [
      { id: "portf-m01", title: "Plan Your Portfolio", lessons: ["plan-your-portfolio"], badge: "Portfolio Planning", badgeCode: "PORTPLAN", skills: ["Decide who your portfolio is for", "Find work you can show", "Choose your best three pieces", "Describe each as problem, action, result and link"] },
      { id: "portf-m02", title: "Show Your Work", lessons: ["show-your-work"], badge: "Show Your Work", badgeCode: "SHOWWORK", skills: ["Host work where it's easy to open", "Take clean screenshots", "Write a short project summary", "Share links safely and protect privacy"] },
      { id: "portf-m03", title: "Build Your Portfolio Page", lessons: ["build-your-portfolio-page"], badge: "Portfolio Page", badgeCode: "PORTSITE", skills: ["Choose a free portfolio tool", "Lay out a one-page portfolio", "Publish it with Google Sites", "Test and share the link"] },
      { id: "portf-m04", title: "Share Your Work on LinkedIn", lessons: ["share-your-work-on-linkedin"], badge: "LinkedIn Posting", badgeCode: "LIPOST", skills: ["Write a hook that earns 'see more'", "Structure a post: story, result, thanks", "Add images and relevant hashtags", "Share achievements without bragging"] },
    ],
  },
  {
    id: "git-and-github-for-beginners",
    slug: "git-and-github-for-beginners",
    format: "short",
    code: "GIT",
    title: "Git & GitHub for Beginners",
    completionBadge: "Git & GitHub",
    summary: "Track your work with Git, put projects on GitHub and turn your profile into a portfolio employers can check.",
    description:
      "Learn what version control is and why every developer and data analyst uses it. Create repositories and commit changes in your browser, publish projects from your computer with GitHub Desktop, and write READMEs that show off your work. Each module takes 15 to 25 minutes, including tasks you do yourself, and ends with a check and a badge.",
    categoryId: "coding",
    difficulty: "beginner",
    level: 1,
    levelLabel: "Beginner",
    isFree: true,
    status: "available",
    skills: ["Version control with Git", "Repositories, commits, push and pull", "Writing a good README", "A GitHub profile that works as a portfolio"],
    prerequisites: ["No experience needed", "A free GitHub account"],
    certificate: shortRules,
    modules: [
      { id: "git-m01", title: "What Git and GitHub Are", lessons: ["what-git-and-github-are"], badge: "Git Basics", badgeCode: "GITBASIC", skills: ["Explain version control", "Tell Git and GitHub apart", "Use the key words: repo, commit, push, pull", "Set up a secure GitHub account"] },
      { id: "git-m02", title: "Your First Repository", lessons: ["your-first-repository"], badge: "First Repository", badgeCode: "FIRSTREP", skills: ["Create a repository", "Add, upload and edit files", "Write clear commit messages", "Read the commit history"] },
      { id: "git-m03", title: "Show Your Projects on GitHub", lessons: ["show-projects-on-github"], badge: "GitHub Portfolio", badgeCode: "GITHUB", skills: ["Push projects with GitHub Desktop", "Know the basic Git commands", "Write a README that sells a project", "Pin projects and write a profile README"] },
    ],
  },
  {
    id: "web-development-for-beginners",
    slug: "web-development-for-beginners",
    format: "short",
    code: "WEB",
    title: "Web Development for Beginners",
    completionBadge: "Web Development Basics",
    summary: "Learn HTML, CSS and JavaScript by building your own personal website, then publish it free with GitHub Pages.",
    description:
      "Build a real website from scratch. Structure a page with HTML, style it with CSS, add interaction with JavaScript, and publish it at your own free web address with GitHub Pages. Each module takes 25 to 30 minutes, including tasks you do yourself, and ends with a check and a badge.",
    categoryId: "coding",
    difficulty: "beginner",
    level: 1,
    levelLabel: "Beginner",
    isFree: true,
    status: "available",
    skills: ["Writing HTML pages", "Styling and layout with CSS", "Adding interaction with JavaScript", "Publishing a website with GitHub Pages"],
    prerequisites: ["No experience needed", "A computer with a free code editor such as VS Code"],
    certificate: shortRules,
    modules: [
      { id: "web-m01", title: "HTML: The Structure", lessons: ["html-the-structure"], badge: "HTML Basics", badgeCode: "HTML", skills: ["Explain how HTML, CSS and JavaScript work together", "Write a valid HTML page", "Use headings, paragraphs, lists and links", "Add images with alt text"] },
      { id: "web-m02", title: "CSS: The Style", lessons: ["css-the-style"], badge: "CSS Basics", badgeCode: "CSS", skills: ["Link a stylesheet", "Use element, class and id selectors", "Understand the box model", "Build a simple responsive layout with flexbox"] },
      { id: "web-m03", title: "JavaScript: The Behaviour", lessons: ["javascript-the-behaviour"], badge: "JavaScript Basics", badgeCode: "JS", skills: ["Use the browser console", "Work with variables, conditions and functions", "Respond to clicks with event listeners", "Read error messages to fix bugs"] },
      { id: "web-m04", title: "Publish Your First Website", lessons: ["publish-your-first-website"], badge: "First Website", badgeCode: "WEBSITE", skills: ["Plan a personal website", "Name files safely for the web", "Publish with GitHub Pages", "Test a live site on a phone"] },
    ],
  },
  {
    id: "python-for-beginners",
    slug: "python-for-beginners",
    format: "short",
    code: "PY",
    title: "Python for Beginners",
    completionBadge: "Python Basics",
    summary: "Write your first Python code in Google Colab: variables, decisions, loops and functions, ending with a budget tracker project.",
    description:
      "Start programming with one of the world's most popular languages, with nothing to install. Learn values and variables, make decisions with if statements, repeat work with loops, and write your own functions, then build a small budget tracker for your portfolio. Each module takes 20 to 25 minutes, including tasks you do yourself, and ends with a check and a badge.",
    categoryId: "python",
    difficulty: "beginner",
    level: 1,
    levelLabel: "Beginner",
    isFree: true,
    status: "available",
    skills: ["Python variables and types", "Conditions, lists and loops", "Writing functions", "Dictionaries and a small project"],
    prerequisites: ["No experience needed", "A free Google account for Google Colab"],
    certificate: shortRules,
    modules: [
      { id: "py-m01", title: "First Steps in Python", lessons: ["first-steps-in-python"], badge: "Python First Steps", badgeCode: "PYSTART", skills: ["Run Python in Google Colab", "Store values in variables", "Know the main data types", "Do maths and format text with f-strings"] },
      { id: "py-m02", title: "Decisions, Lists and Loops", lessons: ["decisions-and-loops"], badge: "Python Logic", badgeCode: "PYLOOPS", skills: ["Make decisions with if, elif and else", "Store values in lists", "Repeat work with for loops", "Use range and zip"] },
      { id: "py-m03", title: "Functions and a Mini Project", lessons: ["functions-and-a-mini-project"], badge: "Python Functions", badgeCode: "PYFUNC", skills: ["Write functions with parameters and return", "Use dictionaries", "Combine it all in a small program", "Save a notebook to GitHub"] },
    ],
  },
  {
    id: "python-for-data-analysis",
    slug: "python-for-data-analysis",
    format: "short",
    code: "PYDA",
    title: "pandas Quick Start",
    completionBadge: "Python Data Analysis",
    summary: "Load, clean, summarise and chart real sales data with pandas in Google Colab.",
    description:
      "Analyse a real-world style sales dataset of over 4,000 orders with pandas. Explore it, fix types and add calculated columns, filter and sort, join tables, summarise with groupby and turn your answers into charts. Each module takes 15 to 25 minutes, including tasks you do yourself, and ends with a check and a badge.",
    categoryId: "python",
    difficulty: "beginner",
    level: 2,
    levelLabel: "Beginner",
    isFree: true,
    status: "available",
    skills: ["Loading and exploring data with pandas", "Cleaning and calculating columns", "Filtering, sorting and grouping", "Joining tables and making charts"],
    prerequisites: ["Python for Beginners, or basic Python", "A free Google account for Google Colab"],
    certificate: shortRules,
    modules: [
      { id: "pyda-m01", title: "Load and Explore Data", lessons: ["load-and-explore-data"], badge: "pandas Basics", badgeCode: "PANDAS", skills: ["Load a CSV into a DataFrame", "Inspect data with head, shape and info", "Summarise with describe", "Count values in a column"] },
      { id: "pyda-m02", title: "Clean, Filter and Calculate", lessons: ["clean-filter-and-calculate"], badge: "Data Cleaning with Python", badgeCode: "PYCLEAN", skills: ["Convert text to dates", "Add calculated columns", "Filter rows with conditions", "Check for missing and duplicate data"] },
      { id: "pyda-m03", title: "Group, Join and Chart", lessons: ["group-join-and-chart"], badge: "Python Data Insights", badgeCode: "PYVIZ", skills: ["Summarise with groupby", "Join tables with merge", "Answer business questions", "Make bar and line charts"] },
    ],
  },
  {
    id: "digital-skills-for-students",
    slug: "digital-skills-for-students",
    format: "short",
    code: "DIGI",
    title: "Digital Skills for Students",
    completionBadge: "Digital Skills",
    summary: "Organise and back up your files, work together in Google Workspace, write professional emails and stay safe online.",
    description:
      "The everyday digital skills every student and new graduate needs. Organise and back up your files in the cloud, collaborate on group work in Google Docs, Sheets and Forms, write emails lecturers and employers take seriously, and protect your accounts from hackers and scams. Each module takes 20 to 25 minutes, including tasks you do yourself, and ends with a check and a badge.",
    categoryId: "study-skills",
    difficulty: "beginner",
    level: 1,
    levelLabel: "Beginner",
    isFree: true,
    status: "available",
    skills: ["File organisation and cloud backup", "Google Docs, Sheets, Forms and Calendar", "Professional email writing", "Online safety and scam awareness"],
    prerequisites: ["No experience needed", "A free Google account"],
    certificate: shortRules,
    modules: [
      { id: "digi-m01", title: "Files and Cloud Storage", lessons: ["files-and-cloud-storage"], badge: "Cloud Storage", badgeCode: "CLOUD", skills: ["Organise files in clear folders", "Name files so you can find them", "Back up to Google Drive or OneDrive", "Share files safely"] },
      { id: "digi-m02", title: "Google Workspace for Students", lessons: ["google-workspace-for-students"], badge: "Google Workspace", badgeCode: "GWORK", skills: ["Collaborate in Google Docs with comments and suggestions", "Track work in Google Sheets", "Collect responses with Google Forms", "Plan a semester in Google Calendar"] },
      { id: "digi-m03", title: "Professional Email", lessons: ["professional-email"], badge: "Professional Email", badgeCode: "EMAIL", skills: ["Choose a professional address", "Write clear subject lines", "Structure a polite, brief email", "Follow up and set a signature"] },
      { id: "digi-m04", title: "Stay Safe Online", lessons: ["stay-safe-online"], badge: "Online Safety", badgeCode: "SAFE", skills: ["Use strong passphrases and a password manager", "Turn on two-step verification", "Spot phishing and student scams", "Manage your digital footprint"] },
    ],
  },
  {
    id: "get-your-first-internship",
    slug: "get-your-first-internship",
    format: "short",
    code: "INTERN",
    title: "Get Your First Internship",
    completionBadge: "Internship Ready",
    summary: "Prepare for SIWES and internships, find local and remote opportunities, apply well and ace the interview.",
    description:
      "A practical guide to landing an internship or SIWES placement. Get your documents ready, find opportunities (including remote ones) and avoid fake offers, write short applications that get read, and prepare for interviews with the STAR method. Each module takes 20 to 25 minutes, including tasks you do yourself, and ends with a check and a badge.",
    categoryId: "career",
    difficulty: "beginner",
    level: 1,
    levelLabel: "Beginner",
    isFree: true,
    status: "available",
    skills: ["Preparing for internships and SIWES", "Finding local and remote opportunities", "Spotting fake offers", "Cover letters and interview answers"],
    prerequisites: ["No experience needed"],
    certificate: shortRules,
    modules: [
      { id: "intern-m01", title: "Get Ready for an Internship", lessons: ["get-ready"], badge: "Internship Prep", badgeCode: "INTREADY", skills: ["Understand internships and SIWES", "Know what employers look for in students", "Prepare your CV, cover letter and documents", "Plan your placement timeline"] },
      { id: "intern-m02", title: "Find Opportunities (Including Remote)", lessons: ["find-opportunities"], badge: "Opportunity Finder", badgeCode: "INTFIND", skills: ["Search job boards and LinkedIn", "Approach organisations directly", "Find remote internships", "Spot and avoid fake offers"] },
      { id: "intern-m03", title: "Apply and Stand Out", lessons: ["apply-and-stand-out"], badge: "Strong Applications", badgeCode: "APPLY", skills: ["Tailor a CV to an advert", "Write a short cover letter", "Track applications", "Follow up politely"] },
      { id: "intern-m04", title: "Ace the Interview", lessons: ["ace-the-interview"], badge: "Interview Ready", badgeCode: "INTERVW", skills: ["Research an organisation", "Answer with the STAR method", "Handle online interviews", "Follow up after an interview"] },
    ],
  },
  {
    id: "freelancing-for-beginners",
    slug: "freelancing-for-beginners",
    format: "short",
    code: "FREEL",
    title: "Freelancing for Beginners",
    completionBadge: "Freelancing Basics",
    summary: "Turn a skill into a clear offer, find clients, price and pitch your work, deliver well and earn great reviews.",
    description:
      "Start earning from a skill you already have. Shape a clear offer and samples, set up profiles on platforms like Fiverr and Upwork, find direct clients, price and pitch your work, get paid safely, and deliver in a way that brings reviews and repeat work. Each module takes 20 to 40 minutes, including tasks you do yourself, and ends with a check and a badge.",
    categoryId: "career",
    difficulty: "beginner",
    level: 1,
    levelLabel: "Beginner",
    isFree: true,
    status: "available",
    skills: ["Packaging a skill as an offer", "Freelance profiles and finding clients", "Pricing and proposals", "Client communication and reviews"],
    prerequisites: ["No experience needed", "One skill you can offer, such as design, writing, video or Excel"],
    certificate: shortRules,
    modules: [
      { id: "freel-m01", title: "Choose Your Skill and Offer", lessons: ["choose-your-skill-and-offer"], badge: "Freelance Offer", badgeCode: "OFFER", skills: ["Pick one skill to sell", "Write a clear one-sentence offer", "Create samples before your first client", "Put samples behind one link"] },
      { id: "freel-m02", title: "Find Clients and Get Paid", lessons: ["find-clients-and-get-paid"], badge: "Client Finder", badgeCode: "CLIENTS", skills: ["Set up a profile on a freelance platform", "Find clients in your network and locally", "Agree safe payment terms", "Avoid client scams"] },
      { id: "freel-m03", title: "Price and Pitch Your Work", lessons: ["price-and-pitch"], badge: "Pricing & Proposals", badgeCode: "PITCH", skills: ["Price per project, per hour or in packages", "Write a short winning proposal", "Agree scope in writing", "Raise prices as you grow"] },
      { id: "freel-m04", title: "Deliver Work and Get Great Reviews", lessons: ["deliver-and-get-reviews"], badge: "Client Delivery", badgeCode: "DELIVER", skills: ["Communicate and update clients", "Deliver professionally", "Handle out-of-scope requests", "Earn reviews and repeat work"] },
    ],
  },
  {
    id: "data-analytics-foundations",
    slug: "data-analytics-foundations",
    code: "DAF",
    title: "Data Analytics Foundations",
    summary: "What data analytics is, how businesses use data to decide, and the core skills you need to start.",
    description:
      "Learn what data analytics is, how businesses use data to make decisions, and the core skills required to begin a career in data analytics. The course ends with your first small analytics project.",
    categoryId: "data-analytics",
    difficulty: "beginner",
    level: 1,
    levelLabel: "Beginner",
    estimatedHours: 6,
    isFree: true,
    status: "available",
    skills: ["How organizations use data", "Types of data", "Databases, cleaning and analysis", "Visualization and business intelligence", "Going from a question to an insight"],
    prerequisites: ["No experience needed", "A spreadsheet program: Google Sheets (free with a Google account) or Microsoft Excel"],
    projectTitle: "Kolanut people review",
    certificate: rules(true),
    modules: [
      ["What is Data Analytics?", "what-is-data-analytics"],
      ["How Businesses Use Data", "how-businesses-use-data"],
      ["Types of Data", "types-of-data"],
      ["Understanding Databases", "understanding-databases"],
      ["Data Cleaning", "data-cleaning"],
      ["Data Analysis", "data-analysis"],
      ["Data Visualization", "data-visualization"],
      ["Business Intelligence", "business-intelligence"],
      ["From Question to Insight", "from-question-to-insight"],
      ["Your First Analytics Project", "your-first-analytics-project"],
    ].map(([title, slug], i) => ({ id: `daf-m${String(i + 1).padStart(2, "0")}`, title, lessons: [slug] })),
  },
  {
    id: "excel-for-data-analysis",
    slug: "excel-for-data-analysis",
    code: "XLS",
    title: "Excel for Data Analysis",
    summary: "Clean, analyse and present business data in Excel, from formulas and XLOOKUP to pivot tables and charts.",
    description:
      "Excel is still where most business analysis happens. Learn to work with real datasets: sort and filter, write the formulas analysts use every day, clean messy data, summarise with pivot tables and present results with clear charts.",
    categoryId: "data-analytics",
    difficulty: "beginner",
    level: 2,
    levelLabel: "Beginner",
    estimatedHours: 7,
    isFree: true,
    status: "available",
    skills: ["Formulas and functions", "IF, SUMIF and COUNTIF", "XLOOKUP", "Data cleaning", "Pivot tables", "Charts"],
    prerequisites: ["Microsoft Excel 2021 or Microsoft 365 (Google Sheets works for most lessons)", "Comfortable using a computer; no Excel experience needed"],
    projectTitle: "Kolanut sales performance review",
    certificate: rules(true),
    modules: [
      ["Excel for Analysts", "excel-for-analysts"],
      ["Working with Data", "working-with-data"],
      ["Sorting and Filtering", "sorting-and-filtering"],
      ["Formulas and Functions", "formulas-and-functions"],
      ["IF, SUMIF, COUNTIF", "if-sumif-countif"],
      ["XLOOKUP", "xlookup"],
      ["Data Cleaning", "data-cleaning"],
      ["Pivot Tables", "pivot-tables"],
      ["Charts and Visualization", "charts-and-visualization"],
      ["Building an Analysis", "building-an-analysis"],
      ["Mini Project", "mini-project"],
    ].map(([title, slug], i) => ({ id: `xls-m${String(i + 1).padStart(2, "0")}`, title, lessons: [slug] })),
  },
  {
    id: "statistics-for-data-analysis",
    slug: "statistics-for-data-analysis",
    code: "STAT",
    title: "Statistics for Data Analysis",
    summary: "The statistics analysts use every week, in Excel or Google Sheets: the right average, spread, outliers, rates, correlation, confidence intervals, tests and trends, on real company data.",
    description:
      "Statistics is what separates a number from a finding. In this course you work in Excel or Google Sheets on the data of Kolanut Distribution, Harbourline Freight and Ashgrove Chambers, and answer the questions managers actually ask: what's typical, how reliable is it, is that difference real, and what happens next? Learn to choose the right average, measure spread and spot outliers, report rates and weighted averages without misleading anyone, read correlations without confusing them with causes, put honest ranges on estimates with confidence intervals, test whether a change is real, and fit trend lines you can quote from. Every lesson ends with tasks checked against the data, and the course ends with a delivery performance review for a logistics company.",
    categoryId: "data-analytics",
    difficulty: "beginner",
    level: 2,
    levelLabel: "Beginner to intermediate",
    estimatedHours: 8,
    isFree: true,
    status: "available",
    skills: [
      "Choosing between mean, median and mode",
      "Measuring spread: IQR, standard deviation and percentiles",
      "Finding and investigating outliers",
      "Percentage points, weighted averages and Simpson's paradox",
      "Correlation, and why it isn't causation",
      "Standard errors and confidence intervals",
      "Testing whether a difference is real",
      "Regression and trend lines",
    ],
    prerequisites: ["Comfortable with spreadsheets: Excel for Data Analysis covers what you need", "No statistics or maths beyond school level"],
    projectTitle: "Harbourline delivery performance review",
    certificate: rules(true),
    modules: [
      ["Statistics for Analysts", "statistics-for-analysts"],
      ["Averages: Mean, Median and Mode", "averages"],
      ["Spread: Range, IQR and Standard Deviation", "spread"],
      ["Distributions and Outliers", "distributions-and-outliers"],
      ["Rates, Percentages and Weighted Averages", "rates-and-weighted-averages"],
      ["Correlation", "correlation"],
      ["Sampling and the Normal Distribution", "sampling-and-the-normal-distribution"],
      ["Confidence Intervals", "confidence-intervals"],
      ["Comparing Groups", "comparing-groups"],
      ["Regression and Trends", "regression-and-trends"],
      ["Final Project", "final-project"],
    ].map(([title, slug], i) => ({ id: `stat-m${String(i + 1).padStart(2, "0")}`, title, lessons: [slug] })),
  },
  {
    id: "sql-for-data-analysis",
    slug: "sql-for-data-analysis",
    code: "SQL",
    title: "SQL for Data Analysis",
    summary: "Query real business data with SQL, from your first SELECT to window functions, using a logistics company's database.",
    description:
      "SQL is how analysts get answers out of databases. In this course you work with Harbourline Freight, a fictional logistics company, and answer the questions its managers actually ask: who ships the most, which routes run late, what customers still owe. Every lesson starts with a business problem, explains the idea in plain language, and gives you queries to write in a live SQL editor in your browser.",
    categoryId: "data-analytics",
    difficulty: "beginner",
    level: 2,
    levelLabel: "Beginner to intermediate",
    estimatedHours: 7,
    isFree: true,
    status: "available",
    skills: [
      "Reading a database schema",
      "Selecting, filtering and sorting data",
      "Aggregating with GROUP BY and HAVING",
      "Joining tables",
      "CASE expressions, subqueries and CTEs",
      "Window functions for rankings and running totals",
      "Turning a business question into a query",
    ],
    prerequisites: ["No prior SQL needed", "Comfortable using a computer and a web browser"],
    projectTitle: "Harbourline Freight operations review",
    certificate: rules(true),
    modules: [
      ["Introduction to Databases", "introduction-to-databases"],
      ["Relational Databases and SQL Tools", "relational-databases-and-sql-tools"],
      ["SELECT", "select"],
      ["WHERE", "where"],
      ["ORDER BY", "order-by"],
      ["LIMIT", "limit"],
      ["Aggregate Functions", "aggregate-functions"],
      ["GROUP BY", "group-by"],
      ["HAVING", "having"],
      ["JOINs", "joins"],
      ["CASE Statements", "case-statements"],
      ["Subqueries", "subqueries"],
      ["CTEs", "ctes"],
      ["Window Functions", "window-functions"],
      ["Business Analysis with SQL", "business-analysis-with-sql"],
      ["Final Project", "final-project"],
    ].map(([title, slug], i) => ({ id: `sql-m${String(i + 1).padStart(2, "0")}`, title, lessons: [slug] })),
  },
  {
    id: "advanced-sql",
    slug: "advanced-sql",
    code: "ASQL",
    title: "Advanced SQL",
    summary: "The SQL working analysts write: NULL and date traps, data quality checks, window functions in depth, cohorts, pivots, recursive queries, performance and the business analyses finance and sales ask for.",
    description:
      "SQL for Data Analysis taught you to get answers out of a database. This course teaches you to get answers you can defend. Back at Harbourline Freight, you'll catch the NULL, integer-division and NOT IN traps that silently give wrong numbers, handle dates and fill missing periods with a calendar, and check a database before you trust it. Then you'll go deeper into window functions (frames, moving averages, LAG and LEAD), return the top rows per group, build cohort and retention tables, compare periods like for like, walk hierarchies with recursive CTEs, read query plans and write queries that stay fast on millions of rows. The course ends with the analyses companies ask for again and again: receivables aging, Pareto concentration and RFM segmentation, and a commercial health check for a board.",
    categoryId: "data-analytics",
    difficulty: "intermediate",
    level: 3,
    levelLabel: "Intermediate to advanced",
    estimatedHours: 6,
    isFree: true,
    status: "available",
    skills: [
      "Avoiding NULL, NOT IN and integer-division traps",
      "Date logic, calendars and 'as of' reporting",
      "Data quality checks in SQL",
      "Window frames, moving averages, LAG and LEAD",
      "Top N per group and deduplication",
      "Cohort and retention analysis",
      "Pivots and like-for-like period comparisons",
      "Self joins, semi- and anti-joins and recursive CTEs",
      "Reading query plans and writing sargable queries",
      "Receivables aging, Pareto and RFM analysis",
    ],
    prerequisites: ["SQL for Data Analysis, or comfort with joins, GROUP BY, CTEs and basic window functions"],
    projectTitle: "Harbourline commercial health check",
    certificate: rules(true),
    modules: [
      ["Readable SQL and NULL Traps", "readable-sql-and-null-traps"],
      ["Date Logic", "date-logic"],
      ["Data Quality Checks", "data-quality-checks"],
      ["Window Functions in Depth", "window-functions-in-depth"],
      ["Top N per Group and Deduplication", "top-n-and-deduplication"],
      ["Cohorts and Retention", "cohorts-and-retention"],
      ["Pivots and Period Comparisons", "pivots-and-period-comparisons"],
      ["Advanced Joins", "advanced-joins"],
      ["Query Performance", "query-performance"],
      ["Business Analysis Patterns", "business-analysis-patterns"],
      ["Final Project", "final-project"],
    ].map(([title, slug], i) => ({ id: `asql-m${String(i + 1).padStart(2, "0")}`, title, lessons: [slug] })),
  },
  {
    id: "data-modelling",
    slug: "data-modelling",
    code: "DMO",
    title: "Data Modelling",
    summary: "Design databases and analytics models that stay correct: entities, keys, relationships, ERDs, normalisation and star schemas.",
    description:
      "Every reliable report sits on a well-designed model. Learn to turn business questions into entities and keys, draw entity-relationship diagrams in crow's-foot notation, normalise away repeated data, and design the star schemas that Power BI and data warehouses run on. Every lesson is built around diagrams, and you practise on real databases in your browser.",
    categoryId: "databases",
    difficulty: "intermediate",
    level: 3,
    levelLabel: "Beginner to intermediate",
    estimatedHours: 6,
    isFree: true,
    status: "available",
    skills: ["Entities, attributes and grain", "Primary and foreign keys", "Cardinality and bridge tables", "Entity-relationship diagrams", "Normalisation (1NF to 3NF)", "Star schemas and slowly changing dimensions"],
    prerequisites: ["Basic SQL (SELECT, WHERE, JOIN) helps; the SQL for Data Analysis course covers it", "No design experience needed"],
    projectTitle: "Ashgrove Chambers data model",
    certificate: rules(true),
    modules: [
      ["What Is a Data Model?", "what-is-a-data-model"],
      ["Entities, Attributes and Grain", "entities-and-attributes"],
      ["Keys", "keys"],
      ["Relationships and Cardinality", "relationships-and-cardinality"],
      ["Entity-Relationship Diagrams", "entity-relationship-diagrams"],
      ["Normalisation", "normalisation"],
      ["Dimensional Modelling", "dimensional-modelling"],
      ["Stars, Snowflakes, Dates and History", "star-snowflake-and-history"],
      ["Modelling in Practice", "modelling-in-practice"],
    ].map(([title, slug], i) => ({ id: `dmo-m${String(i + 1).padStart(2, "0")}`, title, lessons: [slug] })),
  },
  {
    id: "power-bi-fundamentals",
    slug: "power-bi-fundamentals",
    code: "PBI",
    title: "Power BI Fundamentals",
    summary: "Build a data model, write DAX measures and design a dashboard people can use to run a business.",
    description:
      "Power BI turns data into dashboards. Learn the full workflow: import and clean data with Power Query, relate tables in a model, write DAX measures, and design a dashboard that tells a clear business story.",
    categoryId: "business-intelligence",
    difficulty: "beginner",
    level: 2,
    levelLabel: "Beginner to intermediate",
    estimatedHours: 8,
    isFree: true,
    status: "available",
    skills: ["Power Query", "Data modelling and relationships", "DAX measures", "Dashboard design", "Publishing reports"],
    prerequisites: ["Power BI Desktop (free, Windows only)", "Basic Excel is helpful: the Excel course covers it"],
    projectTitle: "Ashgrove Chambers practice dashboard",
    certificate: rules(true),
    modules: [
      ["Introduction to Business Intelligence", "introduction-to-business-intelligence"],
      ["Power BI Interface", "power-bi-interface"],
      ["Importing Data", "importing-data"],
      ["Power Query", "power-query"],
      ["Data Cleaning", "data-cleaning"],
      ["Data Relationships", "data-relationships"],
      ["Data Modelling", "data-modelling"],
      ["DAX Fundamentals", "dax-fundamentals"],
      ["Measures", "measures"],
      ["Visualizations", "visualizations"],
      ["Dashboard Design", "dashboard-design"],
      ["Business Storytelling", "business-storytelling"],
      ["Publishing Reports", "publishing-reports"],
      ["Final Dashboard Project", "final-dashboard-project"],
    ].map(([title, slug], i) => ({ id: `pbi-m${String(i + 1).padStart(2, "0")}`, title, lessons: [slug] })),
  },
  {
    id: "power-bi-dax",
    slug: "power-bi-dax",
    code: "DAX",
    title: "Power BI DAX",
    summary: "DAX in depth: filter and row context, CALCULATE, time intelligence, table functions, ranking, customer analytics and fast, tested measures, on a real distributor's sales data.",
    description:
      "Power BI Fundamentals taught you to write measures. This course teaches you to write measures you can trust and explain. Working on Kolanut Distribution's sales model, you'll learn how DAX really evaluates a formula (filter context, row context and context transition), then use CALCULATE to build shares of a total, a category and a selection. You'll write time intelligence that stays honest when a year is incomplete, split growth into price and volume with variables, count customers that meet a condition with table functions, rank customers and products, and build active, lapsed and Pareto customer measures. The course ends with performance tuning, a testing routine and a commercial dashboard for Kolanut's leadership.",
    categoryId: "business-intelligence",
    difficulty: "intermediate",
    level: 3,
    levelLabel: "Intermediate to advanced",
    estimatedHours: 7,
    isFree: true,
    status: "available",
    skills: [
      "Filter context, row context and context transition",
      "Iterators: SUMX, AVERAGEX, MAXX and RELATED",
      "CALCULATE, KEEPFILTERS, REMOVEFILTERS, ALLEXCEPT and ALLSELECTED",
      "Variables, BLANK handling and readable DAX",
      "Like-for-like time intelligence",
      "Table functions: FILTER, VALUES, SUMMARIZE and DAX query view",
      "Ranking with RANKX and TOPN",
      "Active, lapsed, new customers and Pareto analysis",
      "Performance Analyzer and testing measures",
    ],
    prerequisites: ["Power BI Fundamentals, or comfort with Power Query, relationships and simple measures", "Power BI Desktop (free, Windows only)"],
    projectTitle: "Kolanut commercial dashboard",
    certificate: rules(true),
    modules: [
      ["How DAX Thinks", "how-dax-thinks"],
      ["Filter Context and Row Context", "filter-and-row-context"],
      ["Iterators", "iterators"],
      ["CALCULATE in Depth", "calculate-in-depth"],
      ["Variables, BLANKs and Readable DAX", "variables-and-readable-dax"],
      ["Time Intelligence", "time-intelligence"],
      ["Table Functions", "table-functions"],
      ["Ranking and Top N", "ranking-and-top-n"],
      ["Customer Analytics Patterns", "customer-analytics-patterns"],
      ["Performance and Testing", "performance-and-testing"],
      ["Final Project", "final-project"],
    ].map(([title, slug], i) => ({ id: `dax-m${String(i + 1).padStart(2, "0")}`, title, lessons: [slug] })),
  },
  {
    id: "python-for-data-analytics",
    slug: "python-for-data-analytics",
    code: "PYAN",
    title: "Python for Data Analytics",
    summary: "Analyse real business data in Python and pandas, from your first variable to a finished analysis with charts and findings, in Google Colab.",
    description:
      "Python lets analysts write an analysis once and run it again in seconds, with every step on record. In this course you work in Google Colab, with nothing to install, on the data of Kolanut Distribution and its HR and legal sister datasets. Learn the Python an analyst actually uses, then pandas: loading and exploring data, filtering, calculated columns and dates, cleaning a genuinely messy export, groupby, merging, pivot tables and trends, and charts with titles that say what they show. Every lesson ends with tasks checked against the real data, and the course ends with a customer health review you can put in your portfolio.",
    categoryId: "python",
    difficulty: "beginner",
    level: 2,
    levelLabel: "Beginner to intermediate",
    estimatedHours: 9,
    isFree: true,
    status: "available",
    skills: [
      "Python basics: variables, types, lists, dictionaries, loops and functions",
      "Loading and exploring data with pandas",
      "Filtering, sorting and calculated columns",
      "Cleaning messy data: text, categories, numbers, dates and duplicates",
      "Summarising with groupby and pivot tables",
      "Merging tables safely",
      "Growth rates, year-on-year change and rolling averages",
      "Charts with matplotlib and findings a manager can act on",
    ],
    prerequisites: ["No Python needed", "A free Google account for Google Colab", "Comfortable with spreadsheets; Excel for Data Analysis helps"],
    projectTitle: "Kolanut customer health review",
    certificate: rules(true),
    modules: [
      ["Python and Colab for Analysts", "python-and-colab-for-analysts"],
      ["Lists, Dictionaries, Loops and Functions", "lists-dictionaries-loops-and-functions"],
      ["DataFrames: Load and Explore", "dataframes-load-and-explore"],
      ["Filtering and Sorting", "filtering-and-sorting"],
      ["Calculated Columns and Dates", "calculated-columns-and-dates"],
      ["Cleaning Messy Data", "cleaning-messy-data"],
      ["groupby and Aggregation", "groupby-and-aggregation"],
      ["Merging Tables", "merging-tables"],
      ["Pivot Tables and Trends", "pivot-tables-and-trends"],
      ["Charts with pandas and matplotlib", "charts-with-matplotlib"],
      ["From Question to Insight", "from-question-to-insight"],
      ["Final Project", "final-project"],
    ].map(([title, slug], i) => ({ id: `pyan-m${String(i + 1).padStart(2, "0")}`, title, lessons: [slug] })),
  },
  {
    id: "business-analysis-fundamentals",
    slug: "business-analysis-fundamentals",
    code: "BA",
    title: "Business Analysis Fundamentals",
    summary: "Turn a request into the right change: problem statements, stakeholders, process maps, testable requirements, user stories, KPIs, business cases and acceptance testing, on a real firm's data.",
    description:
      "Business analysts help organisations change for the better. In this course you work with Ashgrove Chambers, a Lagos law firm whose managing partner wants 'a new system' because clients pay late. You'll find the real problem and measure it from the firm's own data, map the stakeholders, interview and observe without leading, map how billing really works and where it breaks, write requirements that can be built and tested, turn them into user stories with Given/When/Then acceptance criteria, define the KPIs that will prove success, build a business case that compares options including doing nothing, and plan testing and adoption. The course ends with a full business analysis pack for a freight company's tracking request.",
    categoryId: "business-analysis",
    difficulty: "beginner",
    level: 2,
    levelLabel: "Beginner to intermediate",
    estimatedHours: 7,
    isFree: true,
    status: "available",
    skills: [
      "Problem statements that separate the need from the solution",
      "Stakeholder analysis and RACI",
      "Interviews, workshops, observation and five whys",
      "Measuring the current state with data",
      "Swimlane process maps, as is and to be",
      "Testable requirements and MoSCoW prioritisation",
      "User stories and Given/When/Then acceptance criteria",
      "KPI definitions, business cases and payback",
      "User acceptance testing, traceability and adoption",
    ],
    prerequisites: ["No experience needed", "Basic Excel helps with the data tasks: Excel for Data Analysis covers it"],
    projectTitle: "Harbourline tracking request: business analysis pack",
    certificate: rules(true),
    modules: [
      ["What Business Analysts Do", "what-business-analysts-do"],
      ["Stakeholders", "stakeholders"],
      ["Eliciting Requirements", "eliciting-requirements"],
      ["The Current State in Numbers", "the-current-state-in-numbers"],
      ["Process Mapping", "process-mapping"],
      ["Writing Requirements", "writing-requirements"],
      ["User Stories and Acceptance Criteria", "user-stories-and-acceptance-criteria"],
      ["Data and Reporting Requirements", "data-and-reporting-requirements"],
      ["The Business Case", "the-business-case"],
      ["Testing and Adoption", "testing-and-adoption"],
      ["Final Project", "final-project"],
    ].map(([title, slug], i) => ({ id: `ba-m${String(i + 1).padStart(2, "0")}`, title, lessons: [slug] })),
  },
  {
    id: "agile-business-analysis",
    slug: "agile-business-analysis",
    code: "ABA",
    title: "Agile Business Analysis",
    summary: "Work as a business analyst in a Scrum team: product vision and outcomes, story maps, splitting, refinement, WSJF, velocity forecasts, flow metrics and pilots, on a real team's backlog.",
    description:
      "Most business analysts now work inside agile teams, where there's no big requirements document and the plan changes every two weeks. In this course you join the team building Kolanut Distribution's ordering app for kiosk owners, with its real backlog and six sprints of history. You'll write a product vision and an outcome-based goal, map the user journey and slice a walking skeleton, split big stories into small valuable ones, run refinement with the three amigos and a definition of ready and done, prioritise with cost of delay and WSJF, forecast the release from the team's real velocity when scope keeps growing, read flow and quality measures without blaming anyone, and design a pilot with success criteria agreed in advance. The course ends with an agile delivery pack for a freight company's delay-notification service.",
    categoryId: "business-analysis",
    difficulty: "intermediate",
    level: 3,
    levelLabel: "Intermediate",
    estimatedHours: 6,
    isFree: true,
    status: "available",
    skills: [
      "Working as a BA in Scrum",
      "Product visions and outcome-based goals",
      "Story mapping and walking skeletons",
      "Splitting stories with proven patterns",
      "Refinement, three amigos, definitions of ready and done",
      "Story points, planning poker and WSJF",
      "Velocity, burn-up charts and release forecasts",
      "Cycle time, throughput and commitment reliability",
      "Sprint reviews and pilots with decision rules",
    ],
    prerequisites: ["Business Analysis Fundamentals, or experience writing requirements and user stories"],
    projectTitle: "Harbourline delay notifications: agile delivery pack",
    certificate: rules(true),
    modules: [
      ["Agile and the Business Analyst", "agile-and-the-business-analyst"],
      ["Product Vision and Outcomes", "vision-and-outcomes"],
      ["Story Mapping", "story-mapping"],
      ["Splitting Stories", "splitting-stories"],
      ["Refinement, Ready and Done", "refinement-ready-and-done"],
      ["Estimation and Prioritisation", "estimation-and-prioritisation"],
      ["Velocity and Release Forecasting", "velocity-and-release-forecasting"],
      ["Measuring Flow and Quality", "measuring-flow-and-quality"],
      ["Reviews, Pilots and Outcomes", "reviews-pilots-and-outcomes"],
      ["Final Project", "final-project"],
    ].map(([title, slug], i) => ({ id: `aba-m${String(i + 1).padStart(2, "0")}`, title, lessons: [slug] })),
  },
  {
    id: "process-improvement-bpmn-lean",
    slug: "process-improvement-bpmn-lean",
    code: "PIL",
    title: "Process Improvement with BPMN and Lean",
    summary: "Find where time and money really go in a process: BPMN models, event logs, value stream maps, the eight wastes, bottlenecks, root causes, future-state design, pilots and control plans, on a real clearance process.",
    description:
      "Most delays in organisations aren't caused by people working slowly; they're caused by work waiting. In this course you improve Harbourline Freight's import clearance at Lagos port, where containers spend more than eight days and customers pay demurrage after three. You'll model the process precisely in BPMN, mine its event log for variants, rework and waiting times, build a value stream map and find a flow efficiency of about 4%, name the wastes, find the bottlenecks with the theory of constraints and Little's law, get to root causes with fishbones, five whys and Pareto analysis, design a future state with Lean patterns, and judge a real pilot with run charts and fair comparisons before putting controls in place. The course ends with an improvement case and an A3 for the next cycle.",
    categoryId: "business-analysis",
    difficulty: "intermediate",
    level: 3,
    levelLabel: "Intermediate",
    estimatedHours: 6,
    isFree: true,
    status: "available",
    skills: [
      "Lean, Six Sigma, DMAIC and PDCA",
      "BPMN: events, gateways, pools, lanes and message flows",
      "Event logs and process mining",
      "Value stream maps and flow efficiency",
      "The eight wastes",
      "Bottlenecks, the theory of constraints and Little's law",
      "Fishbone, five whys and Pareto analysis",
      "Future-state design and benefit estimates",
      "Pilots, run charts and control plans",
    ],
    prerequisites: ["Business Analysis Fundamentals, or experience mapping processes", "Comfortable with Excel, SQL or Python for the data tasks"],
    projectTitle: "Harbourline clearance: the next improvement cycle",
    certificate: rules(true),
    modules: [
      ["Process Improvement and the BA", "process-improvement-and-the-ba"],
      ["BPMN in Depth", "bpmn-in-depth"],
      ["Event Logs and Process Mining", "event-logs-and-process-mining"],
      ["Value Stream Mapping", "value-stream-mapping"],
      ["The Eight Wastes", "the-eight-wastes"],
      ["Bottlenecks and Flow", "bottlenecks-and-flow"],
      ["Root Cause Analysis", "root-cause-analysis"],
      ["Designing the Future State", "designing-the-future-state"],
      ["Pilot, Measure and Sustain", "pilot-measure-and-sustain"],
      ["Final Project", "final-project"],
    ].map(([title, slug], i) => ({ id: `pil-m${String(i + 1).padStart(2, "0")}`, title, lessons: [slug] })),
  },
  {
    id: "data-analyst-capstone",
    slug: "data-analyst-capstone",
    code: "CAP",
    title: "Data Analyst Capstone: End-to-End BI Project",
    summary: "Take a retail chain's raw till export all the way to a reviewed dashboard and a board-ready executive summary, using the tools of your choice.",
    description:
      "The capstone of the Data Analyst track. Voltline Electronics, a chain of eight stores, sends you 18 months of raw till data and one question from its chief executive: what's really driving our 37% growth? You'll plan the analysis, profile and clean a genuinely messy export (a duplicated upload, mixed date formats, inconsistent store names and test transactions), build a model that looks up costs by date and compares sales with monthly targets, decompose the growth, find what's going wrong where, and put a value on missed sales. Then you'll build a dashboard, write an executive summary, prepare for the board's questions and publish the project for your portfolio. Use Excel, Power BI, SQL or Python: the work is assessed on the answers, not the tool.",
    categoryId: "data-analytics",
    difficulty: "intermediate",
    level: 4,
    levelLabel: "Career project",
    estimatedHours: 14,
    isFree: true,
    status: "available",
    skills: [
      "Turning a business brief into an analysis plan",
      "Profiling and cleaning raw data with a quality log",
      "Modelling data at the right grain",
      "Decomposing growth into price, new stores and volume",
      "Judging targets fairly",
      "Estimating lost sales with stated assumptions",
      "Finding-led dashboards and executive summaries",
      "Presenting and publishing a portfolio project",
    ],
    prerequisites: ["The core Data Analyst courses: Excel, SQL and Power BI (or Python)", "Comfort cleaning data and building a dashboard in at least one tool"],
    projectTitle: "Voltline Electronics: commercial review",
    certificate: rules(true),
    modules: [
      ["The Brief and the Plan", "the-brief-and-the-plan"],
      ["Profile the Raw Data", "profile-the-raw-data"],
      ["Clean and Prepare", "clean-and-prepare"],
      ["Model and Measures", "model-and-measures"],
      ["Analyse", "analyse"],
      ["Dashboard and Story", "dashboard-and-story"],
      ["Review, Present and Publish", "review-present-and-publish"],
    ].map(([title, slug], i) => ({ id: `cap-m${String(i + 1).padStart(2, "0")}`, title, lessons: [slug] })),
  },
];
export const findCourseDef = (slug: string | undefined) => COURSES.find((c) => c.slug === slug);
export const categoryName = (id: string) => CATEGORIES.find((c) => c.id === id)?.name ?? id;
