import {
  Award,
  BadgeDollarSign,
  BarChart3,
  Brain,
  Briefcase,
  ChartLine,
  Clapperboard,
  ClipboardList,
  Cloud,
  Code,
  Database,
  Eraser,
  FileCode,
  FileUser,
  FolderOpen,
  GitBranch,
  GitCommitHorizontal,
  Globe,
  GraduationCap,
  Handshake,
  IdCard,
  Images,
  LayoutDashboard,
  Library,
  Lock,
  Mail,
  Megaphone,
  MessageSquareText,
  Mic,
  NotebookPen,
  PackageCheck,
  Paintbrush,
  Palette,
  PenLine,
  Presentation,
  Quote,
  Repeat,
  Rocket,
  Search,
  Send,
  Sheet,
  ShieldCheck,
  Sparkles,
  SquareFunction,
  Table2,
  Tags,
  Target,
  Terminal,
  Users,
  WandSparkles,
  type LucideIcon,
} from "lucide-react";

/** Icon on a module badge, by the module's badge code. */
const BY_CODE: Record<string, LucideIcon> = {
  PROMPT: WandSparkles,
  CLAUDE: Sparkles,
  CHATGPT: MessageSquareText,
  SLIDES: Presentation,
  SOCIAL: Megaphone,
  CANVA: Palette,
  CAPCUT: Clapperboard,
  CV: FileUser,
  LINKEDIN: IdCard,
  EXCEL: BarChart3,
  AIBASICS: Brain,
  STUDYAI: GraduationCap,
  AIRESRCH: Library,
  AIWRITE: PenLine,
  SEARCH: Search,
  SOURCES: ShieldCheck,
  CITE: Quote,
  PORTPLAN: ClipboardList,
  SHOWWORK: Images,
  PORTSITE: Globe,
  LIPOST: Send,
  GITBASIC: GitBranch,
  FIRSTREP: GitCommitHorizontal,
  GITHUB: FolderOpen,
  HTML: FileCode,
  CSS: Paintbrush,
  JS: Code,
  WEBSITE: Rocket,
  PYSTART: Terminal,
  PYLOOPS: Repeat,
  PYFUNC: SquareFunction,
  PANDAS: Sheet,
  PYCLEAN: Eraser,
  PYVIZ: ChartLine,
  CLOUD: Cloud,
  GWORK: Users,
  EMAIL: Mail,
  SAFE: Lock,
  INTREADY: Briefcase,
  INTFIND: Target,
  APPLY: NotebookPen,
  INTERVW: Mic,
  OFFER: Tags,
  CLIENTS: Handshake,
  PITCH: BadgeDollarSign,
  DELIVER: PackageCheck,
};

/** Fallback icon by course category. */
const BY_CATEGORY: Record<string, LucideIcon> = {
  "ai-productivity": Sparkles,
  "design-content": Palette,
  career: FileUser,
  "data-analytics": BarChart3,
  "business-intelligence": LayoutDashboard,
  databases: Database,
  "study-skills": GraduationCap,
  coding: Code,
  python: Terminal,
};

export function badgeIcon(opts: { code?: string | null; categoryId?: string; completion?: boolean }): LucideIcon {
  if (opts.completion) return Award;
  return (opts.code && BY_CODE[opts.code]) || (opts.categoryId && BY_CATEGORY[opts.categoryId]) || Table2;
}
