// Writes supabase/seed.sql from the bundled content (catalogue, lesson files, assessment
// and project), so the database starts with the same courses the site ships with.
// Run with: npm run seed, then paste supabase/seed.sql into the Supabase SQL editor.
//
// Every statement is an upsert, so running it again updates content without touching
// learner progress. Lessons or modules deleted from the files are NOT deleted from the
// database; remove those from /admin.
import { build } from "vite";
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

const root = process.cwd();
const outDir = path.join(root, "node_modules", ".seed");

// The seed must carry every lesson in full, including those the public site build withholds (see vite.config.ts).
process.env.CT_SEED = "1";
await build({
  logLevel: "warn",
  build: { ssr: "scripts/seed-entry.ts", outDir, emptyOutDir: true, copyPublicDir: false },
});
const { BUNDLED_COURSES, BUNDLED_ASSESSMENTS, BUNDLED_PROJECTS, CATEGORIES, TRACKS, programmeCertificateAvailable, PRACTICE_PROJECTS, PROJECT_ANSWERS, gradingKey } = await import(pathToFileURL(path.join(outDir, "seed-entry.js")).href);

const str = (s) => (s === null || s === undefined ? "null" : `'${String(s).replace(/'/g, "''")}'`);
/** Dollar quoting for long Markdown, with a tag that can't appear in the text. */
const doc = (s) => {
  let tag = "md";
  while (s.includes(`$${tag}$`)) tag += "x";
  return `$${tag}$${s}$${tag}$`;
};
const arr = (xs) => (xs.length ? `array[${xs.map(str).join(", ")}]::text[]` : "'{}'::text[]");
const bool = (b) => (b ? "true" : "false");
const num = (n) => (n === undefined || n === null ? "null" : String(Number(n)));
const ts = (v) => (v ? `${str(v)}::timestamptz` : "null");
const json = (v) => `${str(JSON.stringify(v ?? []))}::jsonb`;

/**
 * Starting commercial settings (access, price, delivery, sales content) for a course or a programme. They are written once,
 * while commerce_seeded is false, and never again: after that admins own them, so re-running the seed can't undo a price
 * or an access change made in the dashboard.
 */
function commerceColumns(x, isTrack) {
  const cols = {
    access_type: str(x.access ?? "free"),
    price: num(x.price),
    currency: str(x.currency ?? "NGN"),
    discount_price: num(x.discountPrice),
    discount_active: bool(x.discountActive),
    payment_status: str(x.paymentStatus ?? "active"),
    delivery_type: str(x.deliveryType ?? "self_paced"),
    enrollment_status: str(x.enrollmentStatus ?? "open"),
    enrollment_start: ts(x.enrollmentStart),
    enrollment_end: ts(x.enrollmentEnd),
    community_access: bool(x.communityAccess),
    instructor_support: bool(x.instructorSupport),
    duration_label: x.durationLabel ? str(x.durationLabel) : "null",
    overview: x.overview ? str(x.overview) : "null",
    audience: arr(x.audience ?? []),
    included: arr(x.included ?? []),
    project_previews: json(x.projectPreviews),
    instructor_name: x.instructor?.name ? str(x.instructor.name) : "null",
    instructor_title: x.instructor?.title ? str(x.instructor.title) : "null",
    instructor_bio: x.instructor?.bio ? str(x.instructor.bio) : "null",
    professional_outcome: x.professionalOutcome ? str(x.professionalOutcome) : "null",
    commerce_seeded: "true",
  };
  if (!isTrack) {
    cols.course_type = str(x.courseType ?? "free");
    cols.outcomes = arr(x.outcomes ?? []);
    cols.difficulty_max = x.difficultyMax ? str(x.difficultyMax) : "null";
    cols.duration_weeks = num(x.durationWeeks);
    cols.thumbnail = x.thumbnail ? str(x.thumbnail) : "null";
    cols.faqs = json(x.faqs);
    cols.discount_label = x.discountLabel ? str(x.discountLabel) : "null";
    cols.discount_start = ts(x.discountStart);
    cols.discount_end = ts(x.discountEnd);
  }
  return cols;
}
const commerceUpdate = (table, id, x, isTrack) =>
  `update public.${table} set ${Object.entries(commerceColumns(x, isTrack)).map(([k, v]) => `${k} = ${v}`).join(", ")} where id = ${str(id)} and not commerce_seeded;\n`;

function upsert(table, row, key = "id") {
  const cols = Object.keys(row);
  const updates = cols.filter((c) => c !== key).map((c) => `${c} = excluded.${c}`);
  return `insert into public.${table} (${cols.join(", ")})\nvalues (${Object.values(row).join(", ")})\non conflict (${key}) do update set ${updates.join(", ")};\n`;
}

const out = ["-- Generated by scripts/build-seed.mjs. Do not edit by hand; edit src/content and re-run.", "begin;", ""];

out.push("-- Categories");
CATEGORIES.forEach((c, i) => out.push(upsert("course_categories", { id: str(c.id), name: str(c.name), description: str(c.description), is_future: bool(c.future), position: num(i + 1) })));

for (const c of BUNDLED_COURSES) {
  out.push(`\n-- Course: ${c.title}`);
  out.push(
    upsert("courses", {
      id: str(c.id),
      format: str(c.format ?? "full"),
      completion_badge: str(c.completionBadge),
      slug: str(c.slug),
      code: str(c.code),
      title: str(c.title),
      summary: str(c.summary),
      description: str(c.description),
      category_id: str(c.categoryId),
      difficulty: str(c.difficulty),
      level: num(c.level),
      level_label: str(c.levelLabel),
      estimated_hours: num(c.estimatedHours),
      is_free: bool(c.isFree),
      status: str(c.status),
      published: bool(c.published),
      skills: arr(c.skills),
      prerequisites: arr(c.prerequisites),
      project_title: str(c.projectTitle),
      certificate_enabled: bool(c.certificate.enabled),
      require_all_lessons: bool(c.certificate.requireAllLessons),
      require_exercises: bool(c.certificate.requireExercises),
      require_project: bool(c.certificate.requireProject),
      require_module_badges: bool(c.certificate.requireModuleBadges),
      passing_score: num(c.certificate.passingScore),
      position: num(c.position),
    }),
  );
  out.push(commerceUpdate("courses", c.id, c, false));
  for (const m of c.modules) {
    out.push(
      upsert("course_modules", {
        id: str(m.id),
        course_id: str(c.id),
        title: str(m.title),
        position: num(m.position),
        badge_name: str(m.badge),
        badge_code: str(m.badgeCode),
        skills: arr(m.skills ?? []),
        topics: arr(m.topics ?? []),
      }),
    );
    for (const l of m.lessons) {
      out.push(
        upsert("lessons", {
          id: str(l.id),
          course_id: str(c.id),
          module_id: str(m.id),
          slug: str(l.slug),
          title: str(l.title),
          summary: str(l.summary),
          minutes: num(l.minutes),
          body_md: doc(l.body),
          required: bool(l.required),
          published: bool(l.published),
          position: num(l.position),
          required_exercises: arr(l.requiredExercises),
        }),
      );
    }
  }
}

for (const a of BUNDLED_ASSESSMENTS) {
  out.push(`\n-- Assessment: ${a.title}`);
  out.push(
    upsert("assessments", {
      id: str(a.id),
      course_id: str(a.courseId),
      kind: str(a.kind ?? "final"),
      module_id: str(a.moduleId),
      title: str(a.title),
      passing_score: num(a.passingScore),
      published: "true",
    }),
  );
  a.questions.forEach((q, i) => {
    out.push(upsert("assessment_questions", { id: str(q.id), assessment_id: str(a.id), position: num(i + 1), prompt: str(q.prompt), options: `${str(JSON.stringify(q.options))}::jsonb` }));
    out.push(upsert("assessment_answer_keys", { question_id: str(q.id), correct_index: num(q.answer), explanation: str(q.explanation) }, "question_id"));
  });
}

for (const p of BUNDLED_PROJECTS) {
  out.push(`\n-- Project: ${p.title}`);
  out.push(
    upsert("projects", {
      id: str(p.id),
      course_id: str(p.courseId),
      title: str(p.title),
      summary: str(p.summary),
      brief_md: doc(p.brief),
      tasks: arr(p.tasks),
      datasets: arr(p.datasets),
      rubric: arr(p.rubric ?? []),
      required: bool(p.required),
    }),
  );
}

TRACKS.forEach((t, i) => {
  out.push(`\n-- Track: ${t.title}`);
  out.push(upsert("tracks", { id: str(t.id), slug: str(t.slug), title: str(t.title), summary: str(t.summary), badge_name: str(t.badge), badge_code: str(t.badgeCode), skills: arr(t.skills), position: num(i + 1), published: "true", programme_title: t.programmeTitle ? str(t.programmeTitle) : "null", certificate_enabled: programmeCertificateAvailable(t) ? "true" : "false" }));
  out.push(commerceUpdate("tracks", t.id, t, true));
  // The track's course list is replaced each time, so courses moved or removed in the file don't linger.
  out.push(`delete from public.track_courses where track_id = ${str(t.id)};\n`);
  let pos = 0;
  for (const stage of t.stages)
    for (const item of stage.items)
      if (item.kind === "course")
        out.push(upsert("track_courses", { track_id: str(t.id), course_id: str(item.courseId), stage: str(stage.title), required: bool(item.required !== false), position: num(++pos) }, "track_id, course_id"));
});
// Practice projects (the /projects pages), with the answer key their badges are graded against.
// Needs supabase/migrations/0006_project_badges.sql.
for (const p of PRACTICE_PROJECTS) {
  out.push(`
-- Practice project: ${p.title}`);
  const checks = p.checks.map((c) => gradingKey(c, PROJECT_ANSWERS[c.id]));
  out.push(
    upsert("practice_projects", {
      id: str(p.id),
      title: str(p.title),
      badge_name: str(p.badge.name),
      badge_code: str(p.badge.code),
      skills: arr(p.badge.skills),
      checks: `${str(JSON.stringify(checks))}::jsonb`,
      published: "true",
    }),
  );
}

out.push("", "commit;", "");
fs.writeFileSync(path.join(root, "supabase", "seed.sql"), out.join("\n"));
fs.rmSync(outDir, { recursive: true, force: true });
console.log(`supabase/seed.sql written: ${BUNDLED_COURSES.length} courses, ${TRACKS.length} tracks, ${BUNDLED_COURSES.flatMap((c) => c.modules.flatMap((m) => m.lessons)).length} lessons, ${BUNDLED_ASSESSMENTS.length} assessment(s), ${BUNDLED_PROJECTS.length} project(s).`);
