// Writes supabase/seed.sql from the bundled content (catalogue, lesson files, assessment
// and project), so the database starts with the same courses the site ships with.
// Run with: npm run seed, then paste supabase/seed.sql into the Supabase SQL editor.
//
// Every statement is an upsert, so running it again updates content without touching
// learner progress. Lessons or modules deleted from the files are NOT deleted from the
// database; remove those from /admin.
import { build } from "vite";
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

const root = process.cwd();
const outDir = path.join(root, "node_modules", ".seed");

await build({
  logLevel: "warn",
  build: { ssr: "scripts/seed-entry.ts", outDir, emptyOutDir: true, copyPublicDir: false },
});
const { BUNDLED_COURSES, BUNDLED_ASSESSMENTS, BUNDLED_PROJECTS, CATEGORIES } = await import(pathToFileURL(path.join(outDir, "seed-entry.js")).href);

const str = (s) => (s === null || s === undefined ? "null" : `'${String(s).replace(/'/g, "''")}'`);
/** Dollar quoting for long Markdown, with a tag that can't appear in the text. */
const doc = (s) => {
  let tag = "md";
  while (s.includes(`$${tag}$`)) tag += "x";
  return `$${tag}$${s}$${tag}$`;
};
const arr = (xs) => (xs.length ? `array[${xs.map(str).join(", ")}]::text[]` : "'{}'::text[]");
const bool = (b) => (b ? "true" : "false");
const num = (n) => (n === undefined || n === null ? "null" : String(Number(n)));

function upsert(table, row, key = "id") {
  const cols = Object.keys(row);
  const updates = cols.filter((c) => c !== key).map((c) => `${c} = excluded.${c}`);
  return `insert into public.${table} (${cols.join(", ")})\nvalues (${Object.values(row).join(", ")})\non conflict (${key}) do update set ${updates.join(", ")};\n`;
}

const out = ["-- Generated by scripts/build-seed.mjs. Do not edit by hand; edit src/content and re-run.", "begin;", ""];

out.push("-- Categories");
CATEGORIES.forEach((c, i) => out.push(upsert("course_categories", { id: str(c.id), name: str(c.name), description: str(c.description), is_future: bool(c.future), position: num(i + 1) })));

for (const c of BUNDLED_COURSES) {
  out.push(`\n-- Course: ${c.title}`);
  out.push(
    upsert("courses", {
      id: str(c.id),
      format: str(c.format ?? "full"),
      completion_badge: str(c.completionBadge),
      slug: str(c.slug),
      code: str(c.code),
      title: str(c.title),
      summary: str(c.summary),
      description: str(c.description),
      category_id: str(c.categoryId),
      difficulty: str(c.difficulty),
      level_label: str(c.levelLabel),
      estimated_hours: num(c.estimatedHours),
      is_free: bool(c.isFree),
      status: str(c.status),
      published: bool(c.published),
      skills: arr(c.skills),
      prerequisites: arr(c.prerequisites),
      project_title: str(c.projectTitle),
      certificate_enabled: bool(c.certificate.enabled),
      require_all_lessons: bool(c.certificate.requireAllLessons),
      require_exercises: bool(c.certificate.requireExercises),
      require_project: bool(c.certificate.requireProject),
      require_module_badges: bool(c.certificate.requireModuleBadges),
      passing_score: num(c.certificate.passingScore),
      position: num(c.position),
    }),
  );
  for (const m of c.modules) {
    out.push(
      upsert("course_modules", {
        id: str(m.id),
        course_id: str(c.id),
        title: str(m.title),
        position: num(m.position),
        badge_name: str(m.badge),
        badge_code: str(m.badgeCode),
        skills: arr(m.skills ?? []),
      }),
    );
    for (const l of m.lessons) {
      out.push(
        upsert("lessons", {
          id: str(l.id),
          course_id: str(c.id),
          module_id: str(m.id),
          slug: str(l.slug),
          title: str(l.title),
          summary: str(l.summary),
          minutes: num(l.minutes),
          body_md: doc(l.body),
          required: bool(l.required),
          published: bool(l.published),
          position: num(l.position),
          required_exercises: arr(l.requiredExercises),
        }),
      );
    }
  }
}

for (const a of BUNDLED_ASSESSMENTS) {
  out.push(`\n-- Assessment: ${a.title}`);
  out.push(
    upsert("assessments", {
      id: str(a.id),
      course_id: str(a.courseId),
      kind: str(a.kind ?? "final"),
      module_id: str(a.moduleId),
      title: str(a.title),
      passing_score: num(a.passingScore),
      published: "true",
    }),
  );
  a.questions.forEach((q, i) => {
    out.push(upsert("assessment_questions", { id: str(q.id), assessment_id: str(a.id), position: num(i + 1), prompt: str(q.prompt), options: `${str(JSON.stringify(q.options))}::jsonb` }));
    out.push(upsert("assessment_answer_keys", { question_id: str(q.id), correct_index: num(q.answer), explanation: str(q.explanation) }, "question_id"));
  });
}

for (const p of BUNDLED_PROJECTS) {
  out.push(`\n-- Project: ${p.title}`);
  out.push(
    upsert("projects", {
      id: str(p.id),
      course_id: str(p.courseId),
      title: str(p.title),
      summary: str(p.summary),
      brief_md: doc(p.brief),
      tasks: arr(p.tasks),
      datasets: arr(p.datasets),
      required: bool(p.required),
    }),
  );
}

out.push("", "commit;", "");
fs.writeFileSync(path.join(root, "supabase", "seed.sql"), out.join("\n"));
fs.rmSync(outDir, { recursive: true, force: true });
console.log(`supabase/seed.sql written: ${BUNDLED_COURSES.length} courses, ${BUNDLED_COURSES.flatMap((c) => c.modules.flatMap((m) => m.lessons)).length} lessons, ${BUNDLED_ASSESSMENTS.length} assessment(s), ${BUNDLED_PROJECTS.length} project(s).`);
