import type { AssessmentDef } from "../types";

/** Final assessment for Power BI Fundamentals. Options are shuffled when shown. */
export const PBI_ASSESSMENT: AssessmentDef = {
  id: "power-bi-fundamentals-final",
  courseId: "power-bi-fundamentals",
  title: "Power BI Fundamentals: final assessment",
  passingScore: 60,
  questions: [
    {
      id: "pbiq01",
      prompt: "Which part of Power BI is used to build a report's model and pages on your computer?",
      options: ["Power BI Service", "Power BI Desktop", "Power BI Mobile", "Power Automate"],
      answer: 1,
      explanation: "Reports are built in Desktop and shared through the Service.",
    },
    {
      id: "pbiq02",
      prompt: "In Power Query, what happens to the Applied Steps when the data is refreshed?",
      options: ["They are deleted", "They run again, in order, on the new data", "Only the first step runs", "They must be recreated"],
      answer: 1,
      explanation: "Applied steps are a repeatable recipe.",
    },
    {
      id: "pbiq03",
      prompt: "Which Power Query feature brings a column from another table by matching a key, like XLOOKUP?",
      options: ["Append Queries", "Merge Queries", "Group By", "Unpivot"],
      answer: 1,
      explanation: "Merge joins two queries on matching columns.",
    },
    {
      id: "pbiq04",
      prompt: "Dates like 01/09/2022 load as 9 January instead of 1 September. What should you set when changing the column type?",
      options: ["The locale, for example English (United Kingdom)", "The font", "The chart type", "The column width"],
      answer: 0,
      explanation: "Change Type → Using Locale tells Power Query to read the date day-first.",
    },
    {
      id: "pbiq05",
      prompt: "In Power Query, 'Ada Mart' and 'ADA MART' are treated by Remove Duplicates as:",
      options: ["Duplicates", "Different values", "Errors", "Nulls"],
      answer: 1,
      explanation: "Power Query compares text case-sensitively; standardise case first.",
    },
    {
      id: "pbiq06",
      prompt: "A chart of revenue by region shows the same total on every bar. What should you check first?",
      options: ["The relationship between the customers and orders tables", "The colours of the bars", "The chart title", "The font size"],
      answer: 0,
      explanation: "Without a relationship, the region can't filter the orders, so every bar shows the grand total.",
    },
    {
      id: "pbiq07",
      prompt: "In a star schema, the orders table is:",
      options: ["A dimension table", "The fact table", "The date table", "A measure table"],
      answer: 1,
      explanation: "Orders hold the events and numbers; dimensions describe them.",
    },
    {
      id: "pbiq08",
      prompt: "Month names on an axis sort April, August, December… How do you fix it?",
      options: ["Rename the months", "Sort the Month column by a Month Number column", "Use a pie chart", "Turn off Auto date/time"],
      answer: 1,
      explanation: "Sort by column lets text follow a numeric order.",
    },
    {
      id: "pbiq09",
      prompt: "Which of these should be a measure?",
      options: ["Total revenue", "A customer's name", "An order's date", "A product's category"],
      answer: 0,
      explanation: "Measures are calculations you add up or compare, like totals and averages. Names, dates and categories are columns.",
    },
    {
      id: "pbiq10",
      prompt: "What does DIVIDE([A], [B]) return when [B] is zero?",
      options: ["An error", "Blank (or an alternative result if given)", "Zero always", "Infinity"],
      answer: 1,
      explanation: "DIVIDE handles division by zero safely.",
    },
    {
      id: "pbiq11",
      prompt: "What does SUMX(orders, orders[quantity] * orders[unit_price]) do?",
      options: [
        "Multiplies the two column totals",
        "Multiplies quantity by price on each row, then adds the results",
        "Returns the largest product",
        "Creates a calculated column",
      ],
      answer: 1,
      explanation: "Iterators evaluate the expression row by row, then aggregate.",
    },
    {
      id: "pbiq12",
      prompt: "What does CALCULATE do in DAX?",
      options: ["Works out an expression with changed filters", "Formats a number as currency", "Creates a new table view", "Deletes filters from the report"],
      answer: 0,
      explanation: "CALCULATE evaluates a measure under the filters you give it, for example only 2025.",
    },
    {
      id: "pbiq13",
      prompt: "Which function returns revenue for the same period one year earlier?",
      options: ["SAMEPERIODLASTYEAR, used inside CALCULATE", "SUM", "COUNTROWS", "FORMAT"],
      answer: 0,
      explanation: "CALCULATE([Revenue], SAMEPERIODLASTYEAR('Date'[Date])) shifts the dates back one year.",
    },
    {
      id: "pbiq14",
      prompt: "Which sharing option makes a report public to anyone on the internet?",
      options: ["Share with a colleague", "Publish an app", "Publish to web", "Export to PDF"],
      answer: 2,
      explanation: "Publish to web creates a public link; never use it for company data.",
    },
    {
      id: "pbiq15",
      prompt: "What lets each regional manager see only their own region's data in one shared report?",
      options: ["Bookmarks", "Row-level security", "Slicers", "Drill-through"],
      answer: 1,
      explanation: "RLS filters rows per user based on roles.",
    },
  ],
};
