import type { AssessmentDef } from "../types";

/** Final assessment for Power BI Fundamentals. Options are shuffled when shown. */
export const PBI_ASSESSMENT: AssessmentDef = {
  id: "power-bi-fundamentals-final",
  courseId: "power-bi-fundamentals",
  title: "Power BI Fundamentals: final assessment",
  passingScore: 70,
  questions: [
    {
      id: "pbiq01",
      prompt: "Which part of Power BI is used to build a report's model and pages on your computer?",
      options: ["Power BI Service", "Power BI Desktop", "Power BI Mobile", "Power Automate"],
      answer: 1,
      explanation: "Reports are built in Desktop and shared through the Service.",
    },
    {
      id: "pbiq02",
      prompt: "In Power Query, what happens to the Applied Steps when the data is refreshed?",
      options: ["They are deleted", "They run again, in order, on the new data", "Only the first step runs", "They must be recreated"],
      answer: 1,
      explanation: "Applied steps are a repeatable recipe.",
    },
    {
      id: "pbiq03",
      prompt: "Which Power Query feature brings a column from another table by matching a key, like XLOOKUP?",
      options: ["Append Queries", "Merge Queries", "Group By", "Unpivot"],
      answer: 1,
      explanation: "Merge joins two queries on matching columns.",
    },
    {
      id: "pbiq04",
      prompt: "A column mixes 01/09/2022 and 2022-09-01, written day-first. How should it be converted?",
      options: ["Change Type → Date", "Change Type → Using Locale → Date with English (United Kingdom)", "Replace Values", "Split Column"],
      answer: 1,
      explanation: "The locale tells Power Query to read the day first.",
    },
    {
      id: "pbiq05",
      prompt: "In Power Query, 'Ada Mart' and 'ADA MART' are treated by Remove Duplicates as:",
      options: ["Duplicates", "Different values", "Errors", "Nulls"],
      answer: 1,
      explanation: "Power Query compares text case-sensitively; standardise case first.",
    },
    {
      id: "pbiq06",
      prompt: "A bar chart of revenue by region shows the same value on every bar. What is the most likely cause?",
      options: ["Wrong chart type", "No relationship between the customers and orders tables", "Revenue is formatted as currency", "Too many regions"],
      answer: 1,
      explanation: "Without a relationship, the region filter can't reach the orders.",
    },
    {
      id: "pbiq07",
      prompt: "In a star schema, the orders table is:",
      options: ["A dimension table", "The fact table", "The date table", "A measure table"],
      answer: 1,
      explanation: "Orders hold the events and numbers; dimensions describe them.",
    },
    {
      id: "pbiq08",
      prompt: "Month names on an axis sort April, August, December… How do you fix it?",
      options: ["Rename the months", "Sort the Month column by a Month Number column", "Use a pie chart", "Turn off Auto date/time"],
      answer: 1,
      explanation: "Sort by column lets text follow a numeric order.",
    },
    {
      id: "pbiq09",
      prompt: "Which should be a measure rather than a calculated column?",
      options: ["A size band (Large/Small) for each order line", "Total revenue divided by active customers", "A customer's region copied onto orders", "A year column in the date table"],
      answer: 1,
      explanation: "Ratios of aggregates must respond to filters, so they're measures.",
    },
    {
      id: "pbiq10",
      prompt: "What does DIVIDE([A], [B]) return when [B] is zero?",
      options: ["An error", "Blank (or an alternative result if given)", "Zero always", "Infinity"],
      answer: 1,
      explanation: "DIVIDE handles division by zero safely.",
    },
    {
      id: "pbiq11",
      prompt: "What does SUMX(orders, orders[quantity] * orders[unit_price]) do?",
      options: [
        "Multiplies the two column totals",
        "Multiplies quantity by price on each row, then adds the results",
        "Returns the largest product",
        "Creates a calculated column",
      ],
      answer: 1,
      explanation: "Iterators evaluate the expression row by row, then aggregate.",
    },
    {
      id: "pbiq12",
      prompt: "Which measure gives each category's share of all revenue in a table by category?",
      options: [
        "DIVIDE([Revenue], CALCULATE([Revenue], REMOVEFILTERS(products[category])))",
        "SUM(products[category])",
        "CALCULATE([Revenue], products[category] = \"All\")",
        "[Revenue] / 100",
      ],
      answer: 0,
      explanation: "REMOVEFILTERS gives the all-category total as the denominator.",
    },
    {
      id: "pbiq13",
      prompt: "Which function returns revenue for the same period one year earlier?",
      options: ["TOTALYTD", "SAMEPERIODLASTYEAR inside CALCULATE", "DATEADD with 0 years", "YEAR"],
      answer: 1,
      explanation: "CALCULATE([Revenue], SAMEPERIODLASTYEAR('Date'[Date])).",
    },
    {
      id: "pbiq14",
      prompt: "Which sharing option makes a report public to anyone on the internet?",
      options: ["Share with a colleague", "Publish an app", "Publish to web", "Export to PDF"],
      answer: 2,
      explanation: "Publish to web creates a public link; never use it for company data.",
    },
    {
      id: "pbiq15",
      prompt: "What lets each regional manager see only their own region's data in one shared report?",
      options: ["Bookmarks", "Row-level security", "Slicers", "Drill-through"],
      answer: 1,
      explanation: "RLS filters rows per user based on roles.",
    },
  ],
};
