"""The 50 social media posts: what is on each image, and the caption to post with it.

Edit any wording here, then run `python marketing/posts/build_posts.py` to rebuild the images, captions and gallery.

Layouts: course (a course card), tip (a tip with bullets or a code box), stat (one big number), myth (myth and fact),
list (a checklist), poll (a question with options), steps (three steps), statement (a big headline).
Themes: dark, light, gold, sand.

Rules for this copy: free courses are promoted as free; paid courses show no price; nothing promises a job, an income or a
guaranteed result. Numbers in examples are for practice and are labelled as examples.
"""

U = "academy.cloudtechanalytics.com"

TAGS_DATA = "#CloudTechAcademy #LearnData #DataAnalytics #FreeCourses #Nigeria"
TAGS_STUDENT = "#CloudTechAcademy #StudentLife #CareerTips #LearnOnline #Nigeria"
TAGS_BIZ = "#CloudTechAcademy #BusinessSkills #SmallBusinessNigeria #Entrepreneurship #Nigeria"
TAGS_TRADE = "#CloudTechAcademy #Logistics #SupplyChain #ImportExport #Nigeria"
TAGS_WORK = "#CloudTechAcademy #WorkSkills #ProfessionalDevelopment #LearnOnline #Nigeria"

POSTS = [
    # ---------------------------------------------------------------- free course spotlights
    dict(layout="course", theme="dark", kind="free", tag="Free course", title="Excel for *Data Analysis*", sub="Go beyond the basics.",
         items=["Formulas, IF, SUMIF and XLOOKUP", "Cleaning messy data", "Pivot tables", "Charts that explain your numbers"], cta="Start free",
         path="/courses/excel-for-data-analysis", tags=TAGS_DATA + " #Excel",
         caption="Still only using Excel for lists? 📊\nOur free Excel course takes you from formulas to pivot tables and charts, with practice on real data in your browser.\nGo at your own pace and earn a badge for every module.",
         alt="Course card for the free Excel for Data Analysis course, listing formulas, data cleaning, pivot tables and charts."),
    dict(layout="course", theme="light", kind="free", tag="Free course", title="SQL for *Data Analysis*", sub="Write real queries in your browser.",
         items=["SELECT, WHERE and ORDER BY", "Joins and GROUP BY", "Window functions", "Real company data, nothing to install"], cta="Start free",
         path="/courses/sql-for-data-analysis", tags=TAGS_DATA + " #SQL",
         caption="Want to learn SQL without installing anything? 💻\nWrite real queries in your browser, run them, and see straight away if your answer is right.\nThe course is free.",
         alt="Course card for the free SQL for Data Analysis course."),
    dict(layout="course", theme="gold", kind="free", tag="Free course", title="Power BI *Fundamentals*", sub="Build dashboards people use.",
         items=["Connect and clean data", "Model your tables", "Visuals that answer questions", "A dashboard you can show"], cta="Start free",
         path="/courses/power-bi-fundamentals", tags=TAGS_DATA + " #PowerBI",
         caption="A dashboard is only useful if people understand it. 📈\nLearn Power BI step by step, from messy data to a clear report, in our free course.",
         alt="Course card for the free Power BI Fundamentals course."),
    dict(layout="course", theme="dark", kind="free", tag="Free course", title="Python for *Beginners*", sub="Your first lines of code.",
         items=["Variables, loops and functions", "Working with files and data", "Small programs you can finish", "Practice with instant feedback"], cta="Start free",
         path="/courses/python-for-beginners", tags=TAGS_DATA + " #Python",
         caption="Never written code before? That is fine. 🐍\nOur free Python course starts from the very first line and gives you small programs to finish, so you build confidence as you go.",
         alt="Course card for the free Python for Beginners course."),
    dict(layout="course", theme="sand", kind="free", tag="Free course", title="Data Analytics *Foundations*", sub="Start here if data is new to you.",
         items=["What analysts really do", "Asking the right question", "Spreadsheets and simple analysis", "Telling the story with numbers"], cta="Start free",
         path="/courses/data-analytics-foundations", tags=TAGS_DATA,
         caption="New to data? Start here. 🌱\nData Analytics Foundations explains what analysts do, how to ask a good question and how to turn numbers into a clear message.\nFree, and no experience needed.",
         alt="Course card for the free Data Analytics Foundations course."),
    dict(layout="course", theme="light", kind="free", tag="Free course", title="AI Productivity *Fundamentals*", sub="Use AI well, with your own judgement.",
         items=["Prompts that work", "Working with your own documents", "Research with sources", "Checking answers before you use them"], cta="Start free",
         path="/courses/ai-productivity-fundamentals", tags="#CloudTechAcademy #AI #ChatGPT #Productivity #Nigeria #FreeCourses",
         caption="AI can save you hours, but only if you use it well. 🤖\nLearn to write clear prompts, work with your own documents and check what AI tells you before you rely on it.\nFree course.",
         alt="Course card for the free AI Productivity Fundamentals course."),
    dict(layout="course", theme="dark", kind="free", tag="Free course", title="Career *Essentials*", sub="A CV and LinkedIn that get read.",
         items=["Achievement-focused CV writing", "Tailoring a CV to a job", "A recruiter-ready LinkedIn profile", "Quick analysis in Excel"], cta="Start free",
         path="/courses/career-essentials", tags=TAGS_STUDENT,
         caption="Sending your CV everywhere and hearing nothing back? 📄\nCareer Essentials shows you how to write achievements instead of duties, tailor your CV to each role and build a LinkedIn profile recruiters can read.\nFree.",
         alt="Course card for the free Career Essentials course."),
    dict(layout="course", theme="gold", kind="free", tag="Free course", title="Freelancing for *Beginners*", sub="Turn a skill into a clear offer.",
         items=["Choose a skill and an offer", "Find clients and get paid safely", "Price and pitch your work", "Deliver and earn reviews"], cta="Start free",
         path="/courses/freelancing-for-beginners", tags=TAGS_STUDENT + " #Freelancing",
         caption="Have a skill people could pay for? ✨\nLearn to shape it into a clear offer, find clients, price your work and deliver in a way that earns reviews.\nFree course, four short modules.",
         alt="Course card for the free Freelancing for Beginners course."),

    # ---------------------------------------------------------------- students
    dict(layout="statement", theme="dark", kind="free", kicker="Free for students", title="Student? *Start here.*",
         sub="Study smarter with AI, build a CV that gets read, create a portfolio and go after your first internship.",
         path="/students", tags=TAGS_STUDENT,
         caption="Student? Start here. 📚\nStudy smarter with AI, build a CV that gets read, create a portfolio and go after your first internship. Short courses you can fit around your studies, all free.",
         alt="Headline: Student? Start here. Free skills for school and your first job."),
    dict(layout="list", theme="light", kind="free", title="Before you *graduate*, do these 5 things",
         items=["Write a CV with achievements", "Polish your LinkedIn profile", "Build one small project", "Create a simple portfolio page", "Apply for internships early"],
         path="/students", tags=TAGS_STUDENT,
         caption="A checklist for your last year. ✅\nNone of it needs a big budget, only a bit of time every week. Save this post and tick them off one by one.\nHelp with every step is in our free student courses.",
         alt="Checklist of five things to do before graduating."),
    dict(layout="tip", theme="sand", kind="free", kicker="Tip · Studying with AI", title="Use AI to *learn*, not to copy",
         items=["Ask it to explain a topic in simpler words", "Ask it to quiz you, then check your answers", "Never submit its text as your own work", "Check facts against your notes and textbooks"],
         path="/courses/chatgpt-for-students", tags=TAGS_STUDENT + " #AI",
         caption="AI is a good study partner and a poor ghostwriter. 🧠\nUse it to explain, to quiz you and to give feedback, then do the thinking yourself. Your lecturers can tell the difference, and so will you in the exam.",
         alt="Tip: use AI to learn, not to copy, with four short rules."),
    dict(layout="steps", theme="gold", kind="free", title="Your first internship search, *in 3 steps*",
         items=[("Find the roles", "Search, ask and follow up on companies"), ("Tailor your CV", "Match what each role asks for"), ("Follow up", "A polite message a week later")],
         path="/courses/get-your-first-internship", tags=TAGS_STUDENT,
         caption="Looking for an internship? Keep it simple. 🔎\n1️⃣ Find the roles.\n2️⃣ Tailor your CV to each one.\n3️⃣ Follow up politely a week later.\nOur free course walks you through each step with templates.",
         alt="Three steps for an internship search: find roles, tailor your CV, follow up."),

    # ---------------------------------------------------------------- quick tips
    dict(layout="tip", theme="dark", kind="free", kicker="Excel tip", title="Use *XLOOKUP*, not VLOOKUP",
         code='=XLOOKUP(A2, Products[ID], Products[Price])', items=["Looks left or right", "Exact match by default", "No column numbers to count"],
         path="/courses/excel-for-data-analysis", tags=TAGS_DATA + " #Excel",
         caption="Excel tip: swap VLOOKUP for XLOOKUP. 💡\nIt looks left or right, matches exactly by default and you never have to count columns.\nWe cover it step by step in our free Excel course.",
         alt="Excel tip showing an XLOOKUP formula and three benefits."),
    dict(layout="tip", theme="light", kind="free", kicker="Excel tip", title="Press *F4* to lock a cell",
         code='=B2*$E$1', items=["F4 adds the dollar signs", "Locks the cell when you copy a formula", "Press it again to lock only the row or column"],
         path="/courses/excel-for-data-analysis", tags=TAGS_DATA + " #Excel",
         caption="Excel tip: copied a formula and got the wrong answers? 🔒\nPress F4 while the cell is selected to lock the reference, so it does not move when you copy it down.",
         alt="Excel tip showing a locked cell reference with dollar signs."),
    dict(layout="tip", theme="gold", kind="free", kicker="Excel tip", title="*SUMIF* totals by category",
         code='=SUMIF(A:A,"Cement",B:B)', items=["Adds column B where column A says Cement", "Great for sales by product or region", "SUMIFS handles more than one condition"],
         path="/courses/excel-for-data-analysis", tags=TAGS_DATA + " #Excel",
         caption="Excel tip: need a total for just one category? ➕\nSUMIF adds up only the rows that match. Use SUMIFS when you have more than one condition.",
         alt="Excel tip showing a SUMIF formula."),
    dict(layout="tip", theme="dark", kind="free", kicker="SQL tip", title="*WHERE* filters rows. *HAVING* filters groups.",
         code="SELECT region, SUM(total)\nFROM orders\nWHERE status = 'paid'\nGROUP BY region\nHAVING SUM(total) > 500000;", items=["WHERE works before grouping", "HAVING works after grouping"],
         path="/courses/sql-for-data-analysis", tags=TAGS_DATA + " #SQL",
         caption="SQL tip: the difference between WHERE and HAVING. 🧩\nWHERE filters individual rows before they are grouped. HAVING filters the groups afterwards.",
         alt="SQL tip showing a query with WHERE and HAVING."),
    dict(layout="tip", theme="light", kind="free", kicker="SQL tip", title="Name your columns. Skip *SELECT **",
         code="SELECT customer, total\nFROM orders;", items=["Faster to read and review", "Does not break when columns change", "Returns only what you need"],
         path="/courses/sql-for-data-analysis", tags=TAGS_DATA + " #SQL",
         caption="SQL tip: ask for the columns you need. 🎯\nSELECT * is fine for a quick look, but in real work it is slower, harder to read and can break when a table changes.",
         alt="SQL tip: name your columns instead of using SELECT star."),
    dict(layout="tip", theme="sand", kind="free", kicker="Python tip", title="Use *f-strings* to build text",
         code='name = "Ada"\ntotal = 12500\nprint(f"{name} paid ₦{total:,}")', items=["Put the f before the quotes", "Place variables inside { }", ":, adds thousands commas"],
         path="/courses/python-for-beginners", tags=TAGS_DATA + " #Python",
         caption="Python tip: f-strings make text easy. 🐍\nPut an f before the quote, then place variables inside curly brackets. Add :, to show thousands with commas.",
         alt="Python tip showing an f-string."),
    dict(layout="tip", theme="dark", kind="free", kicker="Data tip", title="Check for *duplicates and blanks* first",
         items=["Count rows before and after cleaning", "Look for blank cells in key columns", "Find duplicate IDs or invoice numbers", "Fix the data before you build the chart"],
         path="/courses/data-analytics-foundations", tags=TAGS_DATA,
         caption="Data tip: before you analyse, look. 👀\nDuplicates and blanks quietly ruin totals and averages. Five minutes of checking saves a wrong report later.",
         alt="Data tip listing four checks to do before analysis."),
    dict(layout="tip", theme="light", kind="free", kicker="Power BI tip", title="Keep your model *simple*",
         items=["One big table of events (the fact table)", "Small tables for products, customers and dates", "Connect them with one-to-many relationships", "Measures answer questions, not columns"],
         path="/courses/power-bi-fundamentals", tags=TAGS_DATA + " #PowerBI",
         caption="Power BI tip: a clean model makes everything easier. 🧱\nKeep one table of events in the middle and small descriptive tables around it. Reports get faster and the numbers get easier to trust.",
         alt="Power BI tip on keeping a simple data model."),
    dict(layout="tip", theme="gold", kind="free", kicker="CV tip", title="Write *achievements*, not duties",
         items=["Weak: Responsible for sales", "Better: Grew weekly sales from ₦200,000 to ₦340,000", "Use numbers: money, time, percentages", "Start lines with action verbs"],
         path="/courses/career-essentials", tags=TAGS_STUDENT,
         caption="CV tip: recruiters skim. 📄\nA line that says what you achieved, with a number, stands out far more than a list of duties.\nWeak: 'Responsible for sales.' Better: 'Grew weekly sales from ₦200,000 to ₦340,000.'",
         alt="CV tip comparing a weak duty line with an achievement line that uses numbers."),
    dict(layout="tip", theme="dark", kind="free", kicker="LinkedIn tip", title="A headline that says *how you help*",
         items=["Not just: Student", "Better: Data analysis student | Excel, SQL, Power BI", "Add a clear photo and a short About", "Show one project you are proud of"],
         path="/courses/career-essentials", tags=TAGS_STUDENT + " #LinkedIn",
         caption="LinkedIn tip: your headline is the first thing people read. 🔗\nSay what you do and the skills you offer, not just your job title or 'student'.",
         alt="LinkedIn tip on writing a headline that says how you help."),
    dict(layout="tip", theme="sand", kind="free", kicker="AI tip", title="A better prompt has *four parts*",
         items=["Role: who the AI should act as", "Task: exactly what you want", "Context: the details it needs", "Format: how you want the answer"],
         path="/courses/ai-productivity-fundamentals", tags="#CloudTechAcademy #AI #ChatGPT #Prompting #Nigeria",
         caption="AI tip: vague question, vague answer. 🤖\nGive it a role, a task, context and a format, and the answers get much more useful. Then check them before you use them.",
         alt="AI tip showing the four parts of a good prompt: role, task, context and format."),

    # ---------------------------------------------------------------- professional course spotlights
    dict(layout="course", theme="dark", kind="paid", tag="Professional course", title="Import, Export & *Mini Importation*", sub="From supplier to your shelf.",
         items=["Find and verify suppliers", "Shipping, documents and customs", "Landed cost and pricing", "Selling what you import"], cta="See the course",
         path="/courses/import-export-mini-importation", tags=TAGS_TRADE,
         caption="Thinking of importing goods? 📦\nLearn to find and check suppliers, ship and clear customs, and work out your real landed cost before you order.\n12 modules with tasks, assessments and a final project.",
         alt="Course card for Import, Export and Mini Importation."),
    dict(layout="course", theme="light", kind="paid", tag="Professional course", title="Procurement & *Sourcing*", sub="Buy the right things, at the right price.",
         items=["RFQs, RFPs and bids", "Supplier evaluation", "Negotiation and purchase orders", "Controls and ethics"], cta="See the course",
         path="/courses/procurement-sourcing", tags=TAGS_TRADE + " #Procurement",
         caption="Procurement quietly decides how much a business spends. 🧾\nLearn how to run a purchase from need to purchase order, compare suppliers fairly and keep the process honest.",
         alt="Course card for Procurement and Sourcing."),
    dict(layout="course", theme="gold", kind="paid", tag="Professional course", title="Logistics & *Freight Forwarding*", sub="How cargo moves, and gets cleared.",
         items=["Air, sea, road and rail", "Shipping documents", "Customs and clearing", "Freight quotations"], cta="See the course",
         path="/courses/logistics-freight-forwarding", tags=TAGS_TRADE,
         caption="Every product you buy has travelled. 🚢\nLearn how cargo moves, which documents it needs, how it clears customs and how a freight quote is built.",
         alt="Course card for Logistics and Freight Forwarding."),
    dict(layout="course", theme="dark", kind="paid", tag="Professional course", title="Supply Chain *Management*", sub="Plan the whole chain.",
         items=["Demand planning and forecasting", "Inventory, EOQ and ABC analysis", "Transport and warehousing", "KPIs and risk"], cta="See the course",
         path="/courses/supply-chain-management", tags=TAGS_TRADE,
         caption="A supply chain is only as strong as its weakest link. 🔗\nLearn to forecast demand, set stock levels, design distribution and measure performance with the right numbers.",
         alt="Course card for Supply Chain Management."),
    dict(layout="course", theme="sand", kind="paid", tag="Professional course", title="Entrepreneurship & *Business Management*", sub="Test the idea before you spend.",
         items=["Validate with real customers", "Business model and plan", "Registration and tax basics", "Pricing, cash flow and growth"], cta="See the course",
         path="/courses/entrepreneurship-business-management", tags=TAGS_BIZ,
         caption="Got a business idea? Test it before you spend on it. 💡\nLearn to talk to customers, build a simple model, plan your money and set the business up properly.",
         alt="Course card for Entrepreneurship and Business Management."),
    dict(layout="course", theme="light", kind="paid", tag="Professional course", title="Business Development & *Sales*", sub="Selling is helping, done well.",
         items=["Find and qualify prospects", "Discovery conversations", "Objections and negotiation", "Pipelines and follow-up"], cta="See the course",
         path="/courses/business-development-sales", tags=TAGS_BIZ + " #Sales",
         caption="Selling is not pushing. It is helping someone solve a problem. 🤝\nLearn to find the right prospects, ask good questions, answer objections honestly and follow up.",
         alt="Course card for Business Development and Sales."),
    dict(layout="course", theme="gold", kind="paid", tag="Professional course", title="Digital Marketing & *Sales*", sub="Reach the right people online.",
         items=["Content and social media", "Paid ads and the numbers", "SEO and local search", "Email, WhatsApp and conversion"], cta="See the course",
         path="/courses/digital-marketing-sales", tags=TAGS_BIZ + " #DigitalMarketing",
         caption="Marketing is more than posting. 📣\nLearn to plan a campaign, write ads, read CPM, CTR and ROAS, win local search and track what works.",
         alt="Course card for Digital Marketing and Sales."),
    dict(layout="course", theme="dark", kind="paid", tag="Professional course", title="E-commerce & *Online Business*", sub="From product to first order.",
         items=["Pick a niche and a product", "Store pages and safe payments", "Delivery and returns", "Marketing and store numbers"], cta="See the course",
         path="/courses/ecommerce-online-business", tags=TAGS_BIZ + " #Ecommerce",
         caption="Want to sell online? 🛒\nLearn to choose a product, set up your store, take payments safely, deliver and reach customers on Instagram, WhatsApp, ads and search.",
         alt="Course card for E-commerce and Online Business."),
    dict(layout="course", theme="sand", kind="paid", tag="Professional course", title="Project *Management*", sub="Plan, run and finish projects.",
         items=["Charter, scope and WBS", "Schedule and critical path", "Budget, risk and change", "Agile and hybrid delivery"], cta="See the course",
         path="/courses/project-management", tags=TAGS_WORK + " #ProjectManagement",
         caption="Projects fail from unclear scope, not bad luck. 🗂️\nLearn to plan, budget, manage risk, lead a team and close a project properly, for any kind of project.",
         alt="Course card for Project Management."),
    dict(layout="course", theme="light", kind="paid", tag="Professional course", title="Human Resources & *People Management*", sub="Hire, manage and keep good people.",
         items=["Recruitment and onboarding", "Performance and development", "Pay, discipline and fair process", "Labour law basics in Nigeria"], cta="See the course",
         path="/courses/human-resources-people-management", tags=TAGS_WORK + " #HR",
         caption="People are usually a business's biggest cost and biggest asset. 👥\nLearn to hire fairly, onboard well, manage performance and handle problems with a fair process.",
         alt="Course card for Human Resources and People Management."),
    dict(layout="course", theme="gold", kind="paid", tag="Professional course", title="Customer Service & *Client Management*", sub="Keep the customers you win.",
         items=["Communication and every channel", "Complaints and difficult people", "Standards, scripts and tickets", "Measuring satisfaction"], cta="See the course",
         path="/courses/customer-service-client-management", tags=TAGS_WORK + " #CustomerService",
         caption="It costs far less to keep a customer than to win a new one. 💬\nLearn to serve well on every channel, handle complaints calmly and measure whether customers are happy.",
         alt="Course card for Customer Service and Client Management."),
    dict(layout="course", theme="dark", kind="paid", tag="Professional course", title="Professional Office *Administration*", sub="The skills that keep an office running.",
         items=["Writing, minutes and reports", "Diary and time management", "Filing, records and software", "Meetings, events and supplies"], cta="See the course",
         path="/courses/professional-office-administration", tags=TAGS_WORK + " #OfficeAdmin",
         caption="When administration works, nobody notices. When it fails, everything slows down. 🗃️\nLearn the skills behind a well-run office, from writing and diaries to records and supplies.",
         alt="Course card for Professional Office Administration."),
    dict(layout="course", theme="light", kind="paid", tag="Professional course", title="Bookkeeping & *Small Business Finance*", sub="Know your numbers.",
         items=["Double-entry bookkeeping", "Reconciliations and adjustments", "Profit and loss, balance sheet, cash flow", "Budgets and tax basics"], cta="See the course",
         path="/courses/bookkeeping-small-business-finance", tags=TAGS_BIZ + " #Bookkeeping",
         caption="Is your business making money, or just handling money? 🧮\nLearn to record transactions, read your statements, plan your cash flow and know what tax records to keep.",
         alt="Course card for Bookkeeping and Small Business Finance."),

    # ---------------------------------------------------------------- business tips and numbers
    dict(layout="stat", theme="dark", kind="paid", big="₦9,750", title="The *real* cost of a ₦7,500 import",
         sub="$5 at ₦1,500 is ₦7,500. Add freight, duty, clearing and transport (about 30% in this example) and the landed cost is ₦9,750 a unit.", note="Example for practice. Real costs vary.",
         path="/courses/import-export-mini-importation", tags=TAGS_TRADE,
         caption="The supplier's price is never your cost. 📦\nIn this practice example, a $5 item at ₦1,500 to the dollar is ₦7,500. After freight, duty, clearing and transport it lands at about ₦9,750.\nWork out your landed cost before you order.",
         alt="Big number ₦9,750 showing the landed cost of a ₦7,500 import in a practice example."),
    dict(layout="stat", theme="gold", kind="paid", big="40% ≠ 67%", title="*Margin* is not *markup*",
         sub="Cost ₦6,000, price ₦10,000. Profit is ₦4,000. That is a 40% margin (of the price) but a 66.7% markup (on the cost).", note="Know which one you are quoting.",
         path="/courses/bookkeeping-small-business-finance", tags=TAGS_BIZ,
         caption="Margin and markup are different numbers. 🧮\nSell something that costs ₦6,000 for ₦10,000 and your profit is ₦4,000. That is 40% of the price (margin) and 66.7% of the cost (markup).\nMixing them up is how people underprice.",
         alt="Comparison of 40 percent margin and 66.7 percent markup on a ₦6,000 item sold at ₦10,000."),
    dict(layout="tip", theme="light", kind="paid", kicker="Business tip", title="Know your *break-even*",
         code="Break-even sales = fixed costs ÷ gross margin\n₦82,000 ÷ 40% = ₦205,000", items=["Fixed costs: rent, wages, depreciation", "Gross margin: profit left after the cost of goods", "Below break-even you lose money"],
         path="/courses/bookkeeping-small-business-finance", tags=TAGS_BIZ,
         caption="Business tip: how much must you sell just to cover your costs? 📊\nDivide your fixed costs by your gross margin. In this example, ₦82,000 of fixed costs at a 40% margin means ₦205,000 of sales.",
         alt="Break-even formula with a worked example."),
    dict(layout="myth", theme="dark", kind="paid", myth="I made a profit, so I must have the cash.",
         fact="Profit is on paper. Stock you have bought, customers who have not paid yet and bills not yet due all move cash and profit at different times. A profitable business can still run out of cash.",
         path="/courses/bookkeeping-small-business-finance", tags=TAGS_BIZ,
         caption="Myth: 'I made a profit, so I must have the cash.' 💸\nFact: profit and cash are different. Stock, unpaid invoices and bills that are not due yet all move them at different times.\nWatch your cash flow every week.",
         alt="Myth and fact about profit and cash."),
    dict(layout="steps", theme="sand", kind="paid", title="Handle a complaint in *4 steps*",
         items=[("Listen", "Let them finish, no interrupting"), ("Apologise", "For the experience, sincerely"), ("Solve", "Offer a fair fix with a time"), ("Thank", "And fix the cause")],
         path="/courses/customer-service-client-management", tags=TAGS_WORK + " #CustomerService",
         caption="A complaint is a customer telling you something went wrong, and that they still care enough to say so. 💬\nListen. Apologise. Solve. Thank. Then fix the cause so it does not happen again.",
         alt="Four steps for handling a complaint: listen, apologise, solve, thank."),
    dict(layout="tip", theme="gold", kind="paid", kicker="Goal tip", title="Make your goal *SMART*",
         items=["Specific: what exactly?", "Measurable: how will you count it?", "Achievable: with your resources", "Relevant: does it matter?", "Time-bound: by when?"],
         path="/courses/entrepreneurship-business-management", tags=TAGS_BIZ,
         caption="Weak goal: 'Grow the business.'\nSMART goal: 'Reach ₦600,000 in monthly sales by the end of month 6.' 🎯\nSpecific, measurable, achievable, relevant, time-bound.",
         alt="SMART goal checklist."),
    dict(layout="tip", theme="dark", kind="paid", kicker="Stock tip", title="When should you *reorder*?",
         code="Reorder point =\nuse per week × (lead time + safety weeks)\n10 × (2 + 1) = 30 reams", items=["Order when stock falls to the reorder point", "Safety stock covers surprises", "Too little means stockouts, too much ties up cash"],
         path="/courses/supply-chain-management", tags=TAGS_TRADE,
         caption="Stock tip: do not wait until you run out. 📦\nMultiply what you use each week by the lead time plus a safety buffer. In this example, 10 reams a week, 2 weeks of lead time and 1 week of safety means you reorder at 30.",
         alt="Reorder point formula with a worked example."),

    # ---------------------------------------------------------------- myths
    dict(layout="myth", theme="light", kind="free", myth="You need a degree or experience to start learning data.",
         fact="You can start with Excel and SQL for free, with no experience, and practise on real data in your browser. Start small and build up.",
         path="/courses?access=free", tags=TAGS_DATA,
         caption="Myth: 'You need a degree to start learning data.' 🚫\nFact: you can start with free Excel and SQL courses today, with no experience, and practise in your browser.",
         alt="Myth and fact about needing a degree to learn data."),
    dict(layout="myth", theme="gold", kind="free", myth="Free courses are not serious.",
         fact="Ours have worked examples, hands-on practice with instant feedback, module checks and badges you can share. Free to start does not mean thin.",
         path="/courses?access=free", tags=TAGS_DATA,
         caption="Myth: 'Free courses are not serious.' 🎓\nFact: ours include worked examples, real practice with instant feedback, checks and badges. Try one lesson and judge for yourself.",
         alt="Myth and fact about free courses."),
    dict(layout="myth", theme="dark", kind="paid", myth="You must buy a lot of stock before you know if an idea will sell.",
         fact="Test small first. Pre-sell, ask for deposits, order samples and place a small first order. Let real customers tell you before you spend big.",
         path="/courses/entrepreneurship-business-management", tags=TAGS_BIZ,
         caption="Myth: 'I must buy plenty of stock to start.' 🛍️\nFact: test small. Pre-sell, take deposits, order a sample and place a small first order. Let customers show you the demand before you commit your money.",
         alt="Myth and fact about testing a business idea before buying stock."),

    # ---------------------------------------------------------------- polls
    dict(layout="poll", theme="sand", kind="free", title="What do you want to *learn first?*", items=["Excel", "SQL", "Power BI", "Python"],
         path="/courses?access=free", tags=TAGS_DATA,
         caption="Which one are you starting with? 👇\nA) Excel\nB) SQL\nC) Power BI\nD) Python\nComment your letter. All four are free.",
         alt="Poll asking which of Excel, SQL, Power BI or Python to learn first."),
    dict(layout="poll", theme="dark", kind="paid", title="Your biggest *business challenge?*", items=["Finding customers", "Pricing", "Cash flow", "Keeping records"],
         path="/courses?area=business", tags=TAGS_BIZ,
         caption="Be honest: what is hardest right now? 💭\nA) Finding customers\nB) Pricing\nC) Cash flow\nD) Keeping records\nComment your letter and we will share tips on the most popular one.",
         alt="Poll asking about your biggest business challenge."),
    dict(layout="poll", theme="light", kind="general", title="Where do you *sell* most?", items=["Instagram", "WhatsApp", "Jumia or Jiji", "Own website"],
         path="/courses/ecommerce-online-business", tags=TAGS_BIZ + " #Ecommerce",
         caption="Where do most of your sales come from? 🛒\nA) Instagram\nB) WhatsApp\nC) Jumia or Jiji\nD) My own website\nComment your letter.",
         alt="Poll asking where you sell the most."),

    # ---------------------------------------------------------------- brand
    dict(layout="statement", theme="gold", kind="free", kicker="Verifiable", title="Every badge has a *public page.*",
         sub="Employers can check a badge or certificate in seconds. No email chasing.",
         path="/verify", tags="#CloudTechAcademy #Credentials #LearnOnline #Nigeria",
         caption="Proof that anyone can check. ✅\nEvery CloudTech Academy badge and certificate has a unique ID and a public verification page, so employers can confirm it in seconds.",
         alt="Headline: every badge has a public page, employers can check it in seconds."),
]

assert len(POSTS) == 50, len(POSTS)
